from common import C

PART1 = [
# =====================================================================
dict(id="landscape", title="The Frontier Landscape (September 2026)",
intro="A snapshot of where frontier and open-weight models stand as of September 2026. This chapter dates quickly; use the trackers at the end to stay current.",
concepts=[
C("Mythos-class tier and trusted access", "Fable / Mythos", 2026, 2026, "B", "enterprise security",
  "Anthropic introduced a capability tier above Opus. The same underlying model ships in two forms: Claude Fable for general use with extra safeguards in biology, cybersecurity and LLM R&D, and Claude Mythos for vetted defenders and partners through Project Glasswing.",
  ["Mythos Preview (April 2026) was first restricted to trusted organisations for cyber defense.",
   "Fable 5 / Mythos 5 launched June 9, 2026; access was suspended June 12 to comply with US export controls and restored July 1 after the controls were lifted.",
   "Fable 5.1 and Mythos 5.1 followed on September 1, 2026, with 1M-token context."],
  "Fable 5.1 is Anthropic's generally available flagship; Opus 5 (July 2026) and Sonnet 5 sit below it.",
  [("D","Anthropic: Project Glasswing","https://www.anthropic.com/glasswing",2026),
   ("D","Anthropic statement on Fable and Mythos access","https://www.anthropic.com/news/fable-mythos-access",2026),
   ("B","DataNorth: Claude Fable 5 and Mythos 5 explained","https://datanorth.ai/news/anthropic-releases-claude-fable-5-and-mythos-5",2026)]),
C("GPT-6 Astra and the Critical cyber threshold", "GPT-6", 2026, 2026, "B", "security enterprise",
  "OpenAI's first GPT-6 generation model, released September 3, 2026. It is the first model OpenAI classified at the Critical cybersecurity level of its Preparedness Framework, so it launched in phases with stronger safeguards and a trusted-access program for defenders.",
  ["Critical means the model can find and exploit unknown vulnerabilities in hardened systems without step-by-step human guidance.",
   "Public versions refuse advanced offensive tasks; vetted defenders get more through OpenAI's trusted-access programs.",
   "Its system card also reported reduced chain-of-thought monitorability, a notable safety signal."],
  "GPT-6 Astra sits above the GPT-5.6 Sol / Terra / Luna tiers.",
  [("B","OpenAI: Path to Astra","https://openai.com/index/path-to-astra/",2026),
   ("D","GPT-6 Astra system card","https://deploymentsafety.openai.com/gpt-6-astra",2026),
   ("B","OpenAI: Safety overview of GPT-6 Astra","https://openai.com/index/safety-overview-gpt-6-astra/",2026),
   ("B","InfoQ: Astra is first model rated Critical for cyber","https://www.infoq.com/news/2026/09/gpt-6-astra-critical-cyber/",2026)]),
C("Tiered access for dual-use models", "trusted access", 2025, 2026, "I", "security enterprise",
  "A 2026 industry pattern: the most cyber-capable models are released in a public version with guardrails and a restricted version for vetted security teams and critical-infrastructure operators.",
  ["Anthropic (Glasswing), OpenAI (trusted access for cyber) and Google (defender-only cyber variants) all adopted versions of it.",
   "It lets defenders patch vulnerabilities before equivalent capabilities spread.",
   "Enterprises now need to track which model variant, safeguards and data-retention terms they are using."],
  "",
  [("D","Anthropic: Project Glasswing","https://www.anthropic.com/glasswing",2026),
   ("B","CSO Online: Astra crosses the Critical cyber threshold","https://www.csoonline.com/article/4218679/openai-launches-gpt-6-astra-its-first-model-to-cross-a-critical-cybersecurity-threshold.html",2026)]),
C("Open-weight frontier models", "", 2023, 2026, "B", "open-source cost",
  "Open-weight models trail the closed frontier by months, not years. 2026's leading families are mostly large sparse MoEs with 1M-token context and permissive licences.",
  ["DeepSeek V4 (April 2026): Pro has 1.6T total / 49B active parameters, Flash has 284B / 13B, both with 1M context, MIT licence.",
   "Other active families: Qwen 3.x, Kimi, GLM-5.x, MiniMax, Mistral Large 3, NVIDIA Nemotron 3, Google Gemma 4.",
   "Open weight does not always mean open source: check licence terms and whether data and code are released."],
  "DeepSeek V4 is the reference open model for long-context efficiency; small open models now run strong coding workloads on a single GPU.",
  [("P","DeepSeek-V4 technical report","https://arxiv.org/abs/2606.19348",2026),
   ("B","HF blog: DeepSeek V4 architecture analysis","https://huggingface.co/blog/ResterChed/deepseek-v4-ga-architecture",2026),
   ("D","Hugging Face models hub","https://huggingface.co/models",2016)]),
C("Model release trackers", "", 2023, 2026, "B", "production",
  "In 2026 frontier labs shipped new models every few weeks. Trackers and independent benchmark aggregators are the practical way to keep up.",
  ["Compare on your own evals, not headline benchmarks.",
   "Watch pricing changes as closely as capability changes: cache-read and small-tier prices fell sharply in 2026."],
  "",
  [("D","Artificial Analysis","https://artificialanalysis.ai",2024),
   ("D","Epoch AI benchmarking hub","https://epoch.ai/benchmarks",2024),
   ("D","LMArena","https://lmarena.ai",2023),
   ("D","OpenRouter model list","https://openrouter.ai/models",2023)]),
]),

# =====================================================================
dict(id="agents", title="Agents and Harnesses",
intro="An agent is a model running in a loop: it reads context, chooses an action, calls a tool, observes the result and repeats. The industry now summarises this as Agent = Model + Harness, and most 2026 engineering effort goes into the harness.",
concepts=[
C("Agent harness", "", 2024, 2026, "B", "foundational production",
  "Everything around the model that turns it into a working agent: the loop, tool definitions, permissions, sandbox, context management, memory, retries, logging and human approval gates.",
  ["Two teams using the same model can get very different results purely from harness design.",
   "Harness setup alone can move benchmark scores by several points.",
   "Harnesses encode assumptions about model weaknesses, so they must be revisited when models improve."],
  "Vendor harnesses (Claude Code, Codex, Gemini CLI) are now exposed as SDKs and managed runtimes so teams can build on them directly.",
  [("B","Martin Fowler: Harness engineering for coding agent users","https://martinfowler.com/articles/harness-engineering.html",2026),
   ("B","Anthropic: Effective harnesses for long-running agents","https://www.anthropic.com/engineering/effective-harnesses-for-long-running-agents",2025),
   ("G","awesome-harness-engineering","https://github.com/ai-boost/awesome-harness-engineering",2026)]),
C("Harness engineering", "", 2026, 2026, "I", "production",
  "The discipline that followed prompt engineering and context engineering: designing environments, constraints, documentation-as-system-of-record, structural tests and feedback loops so agents do reliable work while humans steer.",
  ["OpenAI described a team shipping a roughly million-line product with no hand-written code using this approach.",
   "Core moves: constrain what agents can do, inform them what to do, verify their work, correct mistakes, keep humans at high-stakes gates.",
   "Architecture rules become linters and tests the agent must pass, not wiki pages."],
  "The term entered mainstream use in early 2026 and is now the main focus of agent engineering investment.",
  [("B","OpenAI: Harness engineering","https://openai.com/index/harness-engineering/",2026),
   ("B","Faros: Harness engineering guide","https://www.faros.ai/blog/harness-engineering",2026),
   ("G","awesome-agent-harness","https://github.com/AutoJunjie/awesome-agent-harness",2026)]),
C("Managed agents: decoupling brain, hands and session", "", 2026, 2026, "A", "production enterprise",
  "An architecture where the reasoning loop (brain), the sandboxes and tools that act (hands), and the append-only event log (session) are separate, replaceable services.",
  ["The harness becomes stateless; containers are provisioned only when a tool needs them.",
   "A crash in one sandbox does not lose the session, because state lives in the log.",
   "Enterprises can run the hands inside their own network while the brain runs at the provider."],
  "Anthropic launched Claude Managed Agents on this design in April 2026; Cursor's cloud agents converged on a similar three-layer split.",
  [("B","Anthropic: Scaling Managed Agents","https://anthropic.com/engineering/managed-agents",2026)]),
C("Agentic loop / ReAct", "ReAct", 2022, 2025, "B", "foundational",
  "The basic control pattern: reason about the next step, act by calling a tool, observe the result, and loop until done.",
  ["Modern models interleave thinking between tool calls natively.",
   "A usable coding agent loop fits in about 100 lines of code."],
  "",
  [("P","ReAct paper","https://arxiv.org/abs/2210.03629",2022),
   ("B","Anthropic: Building effective agents","https://www.anthropic.com/engineering/building-effective-agents",2024),
   ("G","mini-swe-agent","https://github.com/SWE-agent/mini-swe-agent",2025)]),
C("Workflows vs. agents", "", 2024, 2025, "B", "foundational production",
  "Workflows run LLM calls through predefined code paths; agents let the model direct its own process. Use the simplest pattern that works.",
  ["Common workflow patterns: prompt chaining, routing, parallelisation, orchestrator-workers, evaluator-optimiser.",
   "Add autonomy only when the path cannot be predicted in advance."],
  "",
  [("B","Anthropic: Building effective agents","https://www.anthropic.com/engineering/building-effective-agents",2024),
   ("G","12-factor agents","https://github.com/humanlayer/12-factor-agents",2025)]),
C("Tool use / function calling", "", 2023, 2025, "B", "foundational",
  "Models emit structured calls (a tool name plus JSON arguments) that the harness executes and returns. Tool design is API design for a non-human user.",
  ["Prefer few, expressive tools over many narrow ones.",
   "Return compact, high-signal output and actionable error messages.",
   "Namespacing and clear descriptions reduce wrong-tool calls."],
  "",
  [("B","Anthropic: Writing effective tools for agents","https://www.anthropic.com/engineering/writing-tools-for-agents",2025),
   ("D","Claude tool use docs","https://docs.claude.com/en/docs/agents-and-tools/tool-use/overview",2024)]),
C("Tool search and programmatic tool calling", "code mode", 2025, 2026, "I", "cost production",
  "Two fixes for tool overload. Tool search loads tool definitions on demand; programmatic tool calling lets the model write a script that calls many tools and returns only the final result.",
  ["Cuts context use and round-trips dramatically for large tool sets.",
   "Deferred tool discovery and stable tool ordering also protect prompt-cache hits."],
  "Now a standard feature in frontier harnesses; MCP servers are increasingly consumed through code rather than direct calls.",
  [("B","Anthropic: Advanced tool use","https://www.anthropic.com/engineering/advanced-tool-use",2025),
   ("B","Anthropic: Code execution with MCP","https://www.anthropic.com/engineering/code-execution-with-mcp",2025),
   ("B","Cloudflare: Code Mode","https://blog.cloudflare.com/code-mode/",2025)]),
C("Multi-agent systems and subagents", "orchestrator-worker", 2023, 2026, "I", "production",
  "A lead agent plans and delegates to subagents with their own clean context windows, then combines condensed results.",
  ["Great for broad research and big codebases; costs more tokens.",
   "Specialised orchestrator models can route work between tools, small models and large models."],
  "Agent teams, swarms and parallel agents in isolated worktrees are routine in 2026 coding tools.",
  [("B","Anthropic: Multi-agent research system","https://www.anthropic.com/engineering/multi-agent-research-system",2025),
   ("D","Claude Code subagents","https://docs.claude.com/en/docs/claude-code/sub-agents",2025),
   ("G","LangGraph","https://github.com/langchain-ai/langgraph",2024)]),
C("Long-running and background agents", "", 2025, 2026, "I", "production",
  "Agents that work for hours or days across many context windows, usually in the cloud while the human does something else.",
  ["Rely on plan files, progress notes, git history, test gates and compaction.",
   "Early models showed context anxiety (wrapping up early near the limit); newer models largely don't, so harness workarounds can become dead weight."],
  "METR's time-horizon measure keeps doubling; multi-hour autonomous runs are normal for frontier models.",
  [("B","Anthropic: Effective harnesses for long-running agents","https://www.anthropic.com/engineering/effective-harnesses-for-long-running-agents",2025),
   ("B","METR: Measuring AI ability to complete long tasks","https://metr.org/blog/2025-03-19-measuring-ai-ability-to-complete-long-tasks/",2025)]),
C("Computer use and browser agents", "CUA", 2024, 2026, "I", "production",
  "Agents that operate a GUI from screenshots with mouse and keyboard actions, or drive a browser through the DOM and accessibility tree.",
  ["Agentic browsers embed this directly in the browser.",
   "Prompt injection from web content is the main security risk."],
  "",
  [("D","Claude computer use tool","https://docs.claude.com/en/docs/agents-and-tools/tool-use/computer-use-tool",2024),
   ("B","OpenAI: Computer-Using Agent","https://openai.com/index/computer-using-agent/",2025),
   ("G","browser-use","https://github.com/browser-use/browser-use",2024),
   ("G","Playwright MCP","https://github.com/microsoft/playwright-mcp",2025)]),
C("Personal agents", "OpenClaw", 2026, 2026, "B", "open-source security",
  "Always-on assistants connected to messaging apps, email, calendars and files that take real actions for a person.",
  ["OpenClaw's viral open-source spread in early 2026 put millions of personal agents into daily use.",
   "Exposed the permission, isolation and injection problems of agents with broad personal access."],
  "",
  [("G","OpenClaw","https://github.com/openclaw/openclaw",2026),
   ("P","SemaClaw: personal agents via harness engineering","https://arxiv.org/abs/2604.11548",2026)]),
C("Agent sandboxes", "", 2024, 2026, "I", "security production",
  "Isolated environments (containers, microVMs, V8 isolates, OS-level sandboxes) where agents run code without endangering the host.",
  ["Filesystem boundaries and network egress controls are the two key levers.",
   "Good sandboxing reduces approval fatigue: fewer prompts, more safety."],
  "Providers now let enterprises run agent sandboxes in their own clouds while the model runs remotely.",
  [("G","Anthropic sandbox-runtime","https://github.com/anthropic-experimental/sandbox-runtime",2025),
   ("G","E2B","https://github.com/e2b-dev/E2B",2023),
   ("G","Daytona","https://github.com/daytonaio/daytona",2024),
   ("G","container-use","https://github.com/dagger/container-use",2025)]),
C("Agent frameworks and SDKs", "", 2023, 2026, "B", "open-source",
  "Libraries that package the loop, tools, memory, handoffs and tracing.",
  ["Vendor SDKs expose the same harness their own products use.",
   "Open frameworks add graphs, durable execution and multi-agent patterns."],
  "",
  [("G","Claude Agent SDK (Python)","https://github.com/anthropics/claude-agent-sdk-python",2025),
   ("G","OpenAI Agents SDK","https://github.com/openai/openai-agents-python",2025),
   ("G","Google ADK","https://github.com/google/adk-python",2025),
   ("G","Microsoft Agent Framework","https://github.com/microsoft/agent-framework",2025),
   ("G","Pydantic AI","https://github.com/pydantic/pydantic-ai",2024),
   ("G","smolagents","https://github.com/huggingface/smolagents",2024),
   ("G","CrewAI","https://github.com/crewAIInc/crewAI",2023),
   ("G","LangChain deepagents","https://github.com/langchain-ai/deepagents",2025)]),
C("Durable execution and agent trajectories", "", 2024, 2026, "A", "production",
  "Persist every step so an agent can crash, pause for approval or wait days, then resume. Trajectory logs also feed memory, evals and training.",
  ["Workflow engines like Temporal are used as agent backbones.",
   "Libraries now normalise session transcripts from many harnesses into one format."],
  "",
  [("D","Temporal","https://temporal.io",2019),
   ("G","LangGraph (persistence)","https://github.com/langchain-ai/langgraph",2024)]),
]),

# =====================================================================
dict(id="protocols", title="Protocols and Interoperability Standards",
intro="Open protocols let agents, tools, apps, editors and payment systems interoperate without bespoke glue. Several now live in neutral foundations.",
concepts=[
C("Model Context Protocol", "MCP", 2024, 2026, "B", "open-standard foundational",
  "An open JSON-RPC protocol connecting AI applications (clients) to tools, resources and prompts exposed by servers. The de facto standard for tool integration across vendors.",
  ["2026-07-28 revision: stateless core (no sessions or initialize handshake), server discovery on demand, cacheable list results, header-based routing.",
   "Formal Extensions framework; MCP Apps and Tasks ship as extensions.",
   "Authorization aligned with OAuth/OIDC: issuer validation, Client ID Metadata Documents, enterprise-managed authorization."],
  "The 2026-07-28 spec is the largest revision since launch, with a 12-month deprecation policy and SDK conformance tiers.",
  [("B","MCP blog: The 2026-07-28 specification","https://blog.modelcontextprotocol.io/posts/2026-07-28/",2026),
   ("B","MCP roadmap (Aug 2026)","https://blog.modelcontextprotocol.io/posts/mcp-roadmap/",2026),
   ("D","modelcontextprotocol.io","https://modelcontextprotocol.io",2024),
   ("G","MCP org (SDKs, servers)","https://github.com/modelcontextprotocol",2024),
   ("B","WorkOS: What changes for agent authentication","https://workos.com/blog/mcp-2026-spec-agent-authentication",2026)]),
C("MCP Apps", "", 2025, 2026, "I", "open-standard",
  "An MCP extension that lets servers return interactive UI rendered in a sandboxed frame, so tools can show forms, charts and pickers inside the chat.",
  ["Standardised as an extension in the 2026-07-28 release."],
  "",
  [("G","MCP ext-apps","https://github.com/modelcontextprotocol/ext-apps",2025)]),
C("MCP Tasks", "", 2025, 2026, "I", "open-standard",
  "An extension for long-running work: a server can accept a job, stream progress and let the client check back or steer mid-flight.",
  ["Paired with subscriptions and progress notifications for push-style updates."],
  "",
  [("B","MCP release candidate notes","https://blog.modelcontextprotocol.io/posts/2026-07-28-release-candidate/",2026)]),
C("Agent2Agent protocol", "A2A", 2025, 2026, "I", "open-standard",
  "An open protocol under the Linux Foundation for agents from different vendors to discover each other via Agent Cards, exchange tasks and stream results.",
  ["MCP is agent-to-tool; A2A is agent-to-agent."],
  "",
  [("S","A2A protocol","https://a2a-protocol.org",2025),
   ("G","A2A repository","https://github.com/a2aproject/A2A",2025)]),
C("Agentic AI Foundation", "AAIF", 2025, 2026, "B", "open-standard",
  "A Linux Foundation home for vendor-neutral agent standards, founded December 2025 with MCP, AGENTS.md and goose.",
  [],
  "",
  [("D","aaif.io","https://aaif.io",2025),
   ("G","goose","https://github.com/block/goose",2025)]),
C("Agent Skills", "SKILL.md", 2025, 2026, "B", "open-standard production",
  "Folders with a SKILL.md (name, description, instructions) plus optional scripts that an agent loads only when relevant (progressive disclosure).",
  ["Published as an open standard; the same skill works across agent products.",
   "Cheap way to package team know-how, house style and workflows."],
  "",
  [("S","agentskills.io","https://agentskills.io",2025),
   ("G","anthropics/skills","https://github.com/anthropics/skills",2025),
   ("B","Anthropic: Equipping agents with Agent Skills","https://www.anthropic.com/engineering/equipping-agents-for-the-real-world-with-agent-skills",2025)]),
C("AGENTS.md", "", 2025, 2026, "B", "open-standard",
  "A Markdown file at the repo root telling coding agents how to build, test and follow conventions: a README for agents.",
  ["CLAUDE.md plays the same role in Claude Code."],
  "",
  [("S","agents.md","https://agents.md",2025),
   ("G","agentsmd/agents.md","https://github.com/agentsmd/agents.md",2025)]),
C("Agent Client Protocol", "ACP", 2025, 2026, "I", "open-standard",
  "An editor-to-agent protocol similar in spirit to LSP, so any coding agent can plug into any editor.",
  [],
  "",
  [("S","agentclientprotocol.com","https://agentclientprotocol.com",2025),
   ("G","agent-client-protocol","https://github.com/zed-industries/agent-client-protocol",2025)]),
C("AG-UI", "", 2025, 2025, "I", "open-standard",
  "An event-based protocol for streaming agent state, tool calls and UI updates between backends and frontends.",
  [],
  "",
  [("D","AG-UI docs","https://docs.ag-ui.com",2025),
   ("G","ag-ui","https://github.com/ag-ui-protocol/ag-ui",2025)]),
C("Agentic commerce protocols", "ACP, AP2, UCP, x402", 2025, 2026, "I", "open-standard enterprise",
  "Standards that let agents shop and pay for users: checkout (Agentic Commerce Protocol), verifiable payment mandates (AP2), merchant integration (UCP) and machine-to-machine payments over HTTP 402 (x402).",
  ["Mandates prove the user authorised a purchase.",
   "x402 enables per-request payments between agents and APIs."],
  "",
  [("G","Agentic Commerce Protocol","https://github.com/agentic-commerce-protocol/agentic-commerce-protocol",2025),
   ("G","AP2","https://github.com/google-agentic-commerce/AP2",2025),
   ("S","Universal Commerce Protocol","https://ucp.dev",2026),
   ("G","x402","https://github.com/coinbase/x402",2025)]),
C("llms.txt", "", 2024, 2025, "B", "open-standard",
  "A proposed file at a website root that gives LLMs a curated Markdown map of the site's most useful content.",
  [],
  "",
  [("S","llmstxt.org","https://llmstxt.org",2024)]),
C("OpenTelemetry GenAI conventions", "OTel GenAI", 2024, 2026, "I", "open-standard production",
  "Standard span and attribute names for LLM calls, tokens, tool invocations and agent steps, so traces from any framework land in any backend.",
  [],
  "",
  [("S","OTel GenAI semantic conventions","https://opentelemetry.io/docs/specs/semconv/gen-ai/",2024)]),
]),

# =====================================================================
dict(id="coding", title="Agentic Coding and Developer Workflow",
intro="Software engineering was the first domain where agents became daily tools at scale. This vocabulary describes how teams now work with them.",
concepts=[
C("Coding agents", "", 2024, 2026, "B", "production open-source",
  "Terminal, IDE, desktop and cloud agents that read a repo, edit files, run commands and tests, and open pull requests.",
  ["They differ mostly in harness, permissions and UX, not the loop itself.",
   "Cross-vendor plugins appeared: e.g. a Codex plugin for Claude Code."],
  "Claude Code, Codex, Gemini CLI, Cursor, Google Antigravity and open tools like OpenHands and OpenCode are the main options in 2026.",
  [("G","Claude Code","https://github.com/anthropics/claude-code",2025),
   ("G","OpenAI Codex CLI","https://github.com/openai/codex",2025),
   ("G","Gemini CLI","https://github.com/google-gemini/gemini-cli",2025),
   ("G","OpenHands","https://github.com/OpenHands/OpenHands",2024),
   ("G","OpenCode","https://github.com/sst/opencode",2025),
   ("G","Aider","https://github.com/Aider-AI/aider",2023)]),
C("Vibe coding", "", 2025, 2025, "B", "",
  "Coined by Andrej Karpathy: building software by describing it and accepting AI output without reading it closely. Fine for prototypes, risky for production.",
  [],
  "",
  [("B","Karpathy's original post","https://x.com/karpathy/status/1886192184808149383",2025),
   ("B","Simon Willison: Not all AI-assisted programming is vibe coding","https://simonwillison.net/2025/Mar/19/vibe-coding/",2025)]),
C("Agentic engineering / Software 3.0", "", 2025, 2026, "I", "production",
  "The professional counterpart to vibe coding: engineers specify intent, design constraints and review outcomes while agents write most of the code.",
  ["Humans steer, agents execute.",
   "Prompts in English become a new kind of program (Software 3.0)."],
  "",
  [("V","Karpathy: Software is changing (again)","https://www.youtube.com/watch?v=LCEmiRjPEtQ",2025),
   ("B","Anthropic: Claude Code best practices","https://www.anthropic.com/engineering/claude-code-best-practices",2025)]),
C("Spec-driven development", "SDD", 2025, 2026, "I", "production",
  "Write a structured spec and plan first, then let agents implement against it, keeping the spec as source of truth.",
  [],
  "",
  [("G","GitHub Spec Kit","https://github.com/github/spec-kit",2025),
   ("D","Kiro","https://kiro.dev",2025)]),
C("Ralph loop", "Ralph Wiggum technique", 2025, 2026, "I", "",
  "Running a coding agent in a simple while-loop against the same prompt and plan file until the job is done.",
  [],
  "",
  [("B","Geoffrey Huntley: Ralph","https://ghuntley.com/ralph/",2025)]),
C("Hooks, plugins and slash commands", "", 2025, 2026, "I", "production",
  "Extension points in coding agents: hooks run deterministic scripts at lifecycle events; plugins bundle commands, subagents, skills, hooks and MCP servers.",
  [],
  "",
  [("D","Claude Code hooks","https://docs.claude.com/en/docs/claude-code/hooks",2025),
   ("D","Claude Code plugins","https://docs.claude.com/en/docs/claude-code/plugins",2025)]),
C("Parallel agents with git worktrees", "", 2025, 2026, "I", "production",
  "Run several agents at once, each in its own worktree or container, then review and merge.",
  [],
  "",
  [("D","git worktree docs","https://git-scm.com/docs/git-worktree",2015),
   ("G","container-use","https://github.com/dagger/container-use",2025)]),
C("The review bottleneck", "", 2026, 2026, "I", "production",
  "When code generation gets cheap, human review becomes the constraint. Changes grow larger and harder to review, and plausible-looking AI code hides subtle bugs.",
  ["Mitigations: agent reviewers, architecture rules as tests, smaller PRs, agents that exercise the app themselves."],
  "",
  [("B","Faros: Harness engineering and the senior engineer tax","https://www.faros.ai/blog/harness-engineering",2026)]),
]),
]
