from common import C

PART2 = [
# =====================================================================
dict(id="context", title="Context, Memory and Retrieval",
intro="What the model sees on each call is the main lever you control at inference time: choosing, compressing and fetching the right information.",
concepts=[
C("Context engineering", "", 2025, 2026, "B", "foundational production",
  "Curating the smallest set of high-signal tokens (instructions, tools, examples, retrieved data, history) that the model needs for its next step.",
  ["Successor to prompt engineering for agents.",
   "Techniques: just-in-time retrieval, compaction, structured notes, subagents with clean context."],
  "",
  [("B","Anthropic: Effective context engineering for AI agents","https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents",2025),
   ("B","LangChain: Context engineering for agents","https://blog.langchain.com/context-engineering-for-agents/",2025)]),
C("Context rot", "", 2025, 2025, "B", "research",
  "Accuracy degrades as input length grows, even well within the advertised window. Long context is not free.",
  [],
  "Million-token windows are standard in 2026, but focused context still usually beats more context.",
  [("B","Chroma Research: Context rot","https://research.trychroma.com/context-rot",2025)]),
C("Compaction and context editing", "", 2025, 2026, "I", "production",
  "Summarising or pruning old turns and stale tool results as a conversation nears the limit, so agents can keep working indefinitely.",
  [],
  "",
  [("B","Anthropic: Managing context on the Claude Developer Platform","https://www.anthropic.com/news/context-management",2025)]),
C("Prompt caching", "", 2024, 2026, "I", "cost production",
  "Reusing the computed KV cache for a repeated prefix across requests to cut latency and cost.",
  ["Harnesses keep prefixes stable (tool order, system prompt) so caches keep hitting."],
  "Cache-read prices were cut steeply again in 2026, making long agent sessions much cheaper.",
  [("D","Claude prompt caching","https://docs.claude.com/en/docs/build-with-claude/prompt-caching",2024)]),
C("Agent memory", "", 2023, 2026, "I", "production research",
  "Persisting facts, preferences and lessons beyond one context window: files the agent writes, vector or graph stores, or self-editing memory blocks.",
  ["Memory quality, provenance and forgetting are now evaluated directly.",
   "Related to continual learning, but done outside the weights."],
  "",
  [("G","Letta (MemGPT)","https://github.com/letta-ai/letta",2023),
   ("G","mem0","https://github.com/mem0ai/mem0",2024),
   ("G","Graphiti","https://github.com/getzep/graphiti",2024)]),
C("Retrieval-augmented generation", "RAG", 2020, 2026, "B", "foundational production",
  "Fetch relevant documents and put them in context before generating.",
  ["Modern stacks: hybrid BM25 + vector search, rerankers, contextual chunk headers, query rewriting."],
  "",
  [("P","Original RAG paper","https://arxiv.org/abs/2005.11401",2020),
   ("B","Anthropic: Contextual retrieval","https://www.anthropic.com/news/contextual-retrieval",2024),
   ("G","LlamaIndex","https://github.com/run-llama/llama_index",2022)]),
C("Agentic search and deep research", "", 2025, 2026, "I", "production",
  "The agent plans queries, reads pages, follows leads and synthesises a cited report over many minutes.",
  ["Many teams prefer agentic grep/file search over vector RAG for code."],
  "",
  [("B","OpenAI: Introducing deep research","https://openai.com/index/introducing-deep-research/",2025),
   ("G","GPT Researcher","https://github.com/assafelovic/gpt-researcher",2023)]),
C("GraphRAG", "", 2024, 2025, "I", "",
  "Build a knowledge graph from a corpus, then retrieve over communities and paths to answer global questions.",
  [],
  "",
  [("G","Microsoft GraphRAG","https://github.com/microsoft/graphrag",2024),
   ("G","LightRAG","https://github.com/HKUDS/LightRAG",2024)]),
C("Embeddings, late interaction and Matryoshka", "", 2020, 2025, "I", "",
  "Dense embeddings map text to vectors; late-interaction models keep per-token vectors; Matryoshka embeddings can be truncated with little loss.",
  [],
  "",
  [("D","MTEB leaderboard","https://huggingface.co/spaces/mteb/leaderboard",2022),
   ("G","ColBERT","https://github.com/stanford-futuredata/ColBERT",2020),
   ("P","Matryoshka representation learning","https://arxiv.org/abs/2205.13147",2022)]),
C("Structured outputs and constrained decoding", "", 2023, 2025, "I", "production",
  "Force output to match a JSON schema or grammar by masking invalid tokens during decoding.",
  [],
  "",
  [("G","XGrammar","https://github.com/mlc-ai/xgrammar",2024),
   ("G","Outlines","https://github.com/dottxt-ai/outlines",2023),
   ("D","OpenAI structured outputs","https://platform.openai.com/docs/guides/structured-outputs",2024)]),
]),

# =====================================================================
dict(id="reasoning", title="Reasoning and Post-Training",
intro="Most capability gains since late 2024 came from post-training. In 2026 the recipe shifted again: many RL specialists, merged by on-policy distillation.",
concepts=[
C("Reasoning models and test-time compute", "", 2024, 2026, "B", "foundational",
  "Models trained to think in long chains before answering; accuracy scales with thinking tokens, a second scaling axis beyond model size.",
  [],
  "In 2026 general and reasoning lines have merged: one model decides how much to think per request.",
  [("B","OpenAI: Learning to reason with LLMs","https://openai.com/index/learning-to-reason-with-llms/",2024),
   ("P","Scaling test-time compute optimally","https://arxiv.org/abs/2408.03314",2024),
   ("P","DeepSeek-R1","https://arxiv.org/abs/2501.12948",2025)]),
C("Thinking budgets, adaptive thinking and effort", "", 2025, 2026, "I", "cost production",
  "Controls that set how much a model thinks per request, trading latency and cost for quality. Interleaved thinking lets it reason between tool calls.",
  [],
  "Adjustable reasoning effort inside a conversation became a standard API feature in 2026.",
  [("D","Claude extended thinking docs","https://docs.claude.com/en/docs/build-with-claude/extended-thinking",2025),
   ("P","s1: simple test-time scaling","https://arxiv.org/abs/2501.19393",2025)]),
C("RL with verifiable rewards", "RLVR", 2024, 2026, "I", "foundational",
  "Reinforcement learning where rewards come from checkers (tests, answer matching, verifiers) instead of a learned preference model.",
  ["Coined in the Tulu 3 work (2024), popularised by DeepSeek-R1.",
   "RL is now a large and growing share of frontier training compute."],
  "",
  [("P","Tulu 3","https://arxiv.org/abs/2411.15124",2024),
   ("D","RLHF Book (Nathan Lambert)","https://rlhfbook.com",2024)]),
C("Multi-teacher on-policy distillation", "MOPD", 2026, 2026, "A", "research",
  "The 2026 post-training pattern: train several domain specialists with SFT then RL, then train one general student on its own samples while minimising reverse-KL to the relevant teacher token by token.",
  ["Avoids capability trade-offs from mixing math, code and agentic RL in one run.",
   "Specialists can be built in parallel by different teams.",
   "Introduced with Xiaomi MiMo, scaled to 10+ teachers by DeepSeek V4 and Nemotron 3 Ultra."],
  "Now the default final stage in several frontier open recipes.",
  [("D","RLHF Book course: Frontier post-training recipe survey","https://rlhfbook.com/teach/course/conversation-01/",2026),
   ("B","Hugging Face: Distillation in 2026","https://huggingface.co/blog/sergiopaniego/distillation-2026",2026),
   ("B","Thinking Machines: On-policy distillation","https://thinkingmachines.ai/blog/on-policy-distillation/",2025)]),
C("GRPO and its successors", "GRPO, DAPO, GSPO", 2024, 2025, "A", "research",
  "Group Relative Policy Optimization drops PPO's value network and scores samples against their group. Successors fix length bias, clipping and MoE instability.",
  [],
  "",
  [("P","DeepSeekMath (GRPO)","https://arxiv.org/abs/2402.03300",2024),
   ("P","DAPO","https://arxiv.org/abs/2503.14476",2025),
   ("P","GSPO","https://arxiv.org/abs/2507.18071",2025),
   ("P","Dr. GRPO","https://arxiv.org/abs/2503.20783",2025)]),
C("RL environments and verifiers", "", 2025, 2026, "A", "research enterprise",
  "Packaged tasks plus graders used to train agents. In 2026 environments look like sandboxed replicas of enterprise software, and verifier quality is seen as the next ceiling on agent progress.",
  ["Labs spend heavily on environments; a market of environment vendors has formed.",
   "As agents improve, verifiers must improve faster to avoid reward hacking."],
  "",
  [("G","Prime Intellect verifiers","https://github.com/PrimeIntellect-ai/verifiers",2025),
   ("G","OpenEnv","https://github.com/meta-pytorch/OpenEnv",2025),
   ("G","verl","https://github.com/volcengine/verl",2024),
   ("G","SkyRL","https://github.com/NovaSky-AI/SkyRL",2025),
   ("B","Prolific: RL environments for agentic AI (2026 guide)","https://www.prolific.com/resources/rl-environments-for-agentic-ai-the-2026-guide-to-building-and-deploying-enterprise-rl-environments",2026)]),
C("RLHF, DPO and preference optimization", "", 2022, 2025, "I", "foundational",
  "Aligning outputs to human preferences with a reward model plus RL, or directly from preference pairs (DPO).",
  [],
  "",
  [("P","InstructGPT","https://arxiv.org/abs/2203.02155",2022),
   ("P","DPO","https://arxiv.org/abs/2305.18290",2023),
   ("G","Hugging Face TRL","https://github.com/huggingface/trl",2020)]),
C("Constitutional AI and model specs", "", 2022, 2026, "I", "",
  "Training behaviour from a written set of principles with AI feedback. Labs now publish the documents that define model character and priorities.",
  [],
  "",
  [("P","Constitutional AI","https://arxiv.org/abs/2212.08073",2022),
   ("D","Claude's constitution","https://www.anthropic.com/constitution",2026)]),
C("Process reward models", "PRM", 2023, 2025, "A", "research",
  "Reward models that grade each reasoning step rather than only the final answer.",
  [],
  "",
  [("P","Let's verify step by step","https://arxiv.org/abs/2305.20050",2023)]),
C("Reward hacking", "", 2016, 2026, "I", "security research",
  "The policy exploits flaws in the reward (special-casing tests, editing graders) instead of solving the task; learned hacking can generalise to broader misbehaviour.",
  [],
  "",
  [("B","Lilian Weng: Reward hacking","https://lilianweng.github.io/posts/2024-11-28-reward-hacking/",2024),
   ("B","Anthropic: Emergent misalignment from reward hacking","https://www.anthropic.com/research/emergent-misalignment-reward-hacking",2025)]),
C("Self-play and self-generated curricula", "", 2025, 2025, "A", "research",
  "Models propose tasks, solve them and learn from verified results.",
  [],
  "",
  [("P","Absolute Zero","https://arxiv.org/abs/2505.03335",2025)]),
C("Continual learning", "", 2024, 2026, "A", "research",
  "Updating a deployed model with new knowledge and skills without catastrophic forgetting.",
  ["Approaches: replay, regularisation, architectural expansion, self-distillation, nested optimisation.",
   "Widely named as a key 2026 frontier for agents that improve on the job."],
  "",
  [("P","Survey: Continual learning in LLMs (2026)","https://arxiv.org/abs/2603.12658",2026),
   ("B","Google Research: Nested learning","https://research.google/blog/introducing-nested-learning-a-new-ml-paradigm-for-continual-learning/",2025)]),
]),

# =====================================================================
dict(id="arch", title="Model Architectures",
intro="Transformers still dominate, but 2026 models mix sparse experts, compressed and sparse attention, hybrid linear layers and new residual schemes.",
concepts=[
C("Mixture of Experts", "MoE", 2017, 2026, "B", "foundational cost",
  "Tokens route to a few expert feed-forward blocks out of many, so total parameters grow while compute per token stays small.",
  ["Fine-grained experts plus a shared expert is the common 2026 layout.",
   "Expert parallelism needs fast all-to-all communication."],
  "Frontier open models reach 1.6T to 2.8T total parameters with roughly 3% active per token.",
  [("B","Hugging Face: MoE explained","https://huggingface.co/blog/moe",2023),
   ("P","DeepSeek-V3","https://arxiv.org/abs/2412.19437",2024),
   ("G","DeepEP","https://github.com/deepseek-ai/DeepEP",2025)]),
C("GQA and Multi-head Latent Attention", "GQA, MLA", 2023, 2025, "I", "cost",
  "Two ways to shrink the KV cache: share keys/values across head groups (GQA) or compress them into a low-rank latent (MLA).",
  [],
  "",
  [("P","GQA","https://arxiv.org/abs/2305.13245",2023),
   ("P","DeepSeek-V2 (MLA)","https://arxiv.org/abs/2405.04434",2024)]),
C("Sparse and compressed attention", "NSA, DSA, CSA, HCA", 2025, 2026, "A", "research cost",
  "Attend only to selected tokens or compressed summaries of blocks to make long context cheap.",
  ["DeepSeek V4 interleaves Compressed Sparse Attention (compress KV along the sequence, then top-k select) with Heavily Compressed Attention.",
   "Reported KV-cache reductions near 98% versus standard GQA make 1M-token inference affordable."],
  "DeepSeek V4's CSA/HCA hybrid replaced MLA and is the most detailed public long-context design in 2026.",
  [("P","Native Sparse Attention","https://arxiv.org/abs/2502.11089",2025),
   ("G","DeepSeek-V3.2-Exp (DSA)","https://github.com/deepseek-ai/DeepSeek-V3.2-Exp",2025),
   ("P","DeepSeek-V4 report","https://arxiv.org/abs/2606.19348",2026)]),
C("Manifold-constrained hyper-connections", "mHC", 2026, 2026, "A", "research",
  "Replaces plain residual connections with learned mixtures over several parallel residual streams, projected onto a constrained manifold to keep signals stable in very deep, very large models.",
  ["Used in DeepSeek V4 to stabilise training at trillion-parameter scale."],
  "",
  [("P","DeepSeek-V4 report","https://arxiv.org/abs/2606.19348",2026)]),
C("Hybrid linear-attention and state space models", "Mamba, Gated DeltaNet", 2023, 2026, "A", "research cost",
  "Mix a few full-attention layers with many linear-time layers for long context at lower cost.",
  [],
  "A leading 2026 trend: Qwen 3.x, Nemotron 3, Kimi Linear and others ship hybrids.",
  [("G","Mamba","https://github.com/state-spaces/mamba",2023),
   ("G","Gated DeltaNet","https://github.com/NVlabs/GatedDeltaNet",2024),
   ("G","Kimi Linear","https://github.com/MoonshotAI/Kimi-Linear",2025),
   ("G","flash-linear-attention","https://github.com/fla-org/flash-linear-attention",2023)]),
C("Diffusion language models", "dLLM", 2025, 2026, "A", "research cost",
  "Generate text by iteratively denoising blocks in parallel rather than left to right, for much faster decoding.",
  [],
  "Commercial diffusion LLMs now offer very low-cost, high-speed endpoints.",
  [("G","LLaDA","https://github.com/ML-GSAI/LLaDA",2025),
   ("D","Gemini Diffusion","https://deepmind.google/models/gemini-diffusion/",2025),
   ("D","Inception Labs (Mercury)","https://www.inceptionlabs.ai",2025)]),
C("Multi-token prediction and speculative decoding", "MTP", 2023, 2026, "I", "cost",
  "Predict several tokens at once, or let a cheap draft propose tokens that the big model verifies in one pass.",
  [],
  "",
  [("P","Speculative decoding","https://arxiv.org/abs/2211.17192",2022),
   ("G","EAGLE","https://github.com/SafeAILab/EAGLE",2024),
   ("P","Multi-token prediction","https://arxiv.org/abs/2404.19737",2024)]),
C("Long-context methods", "RoPE, YaRN", 2021, 2026, "I", "",
  "Rotary embeddings and scaling tricks that extend context windows; combined with sparse attention and KV compression to reach 1M tokens.",
  [],
  "1M-token context is the default for 2026 frontier models.",
  [("P","RoFormer (RoPE)","https://arxiv.org/abs/2104.09864",2021),
   ("G","YaRN","https://github.com/jquesnelle/yarn",2023)]),
C("Attention sinks", "", 2023, 2025, "A", "research",
  "Models park attention on the first tokens; keeping them (or learned sink logits) stabilises long generation.",
  [],
  "",
  [("P","StreamingLLM","https://arxiv.org/abs/2309.17453",2023)]),
C("Tokenizer-free and byte-level models", "BLT", 2024, 2025, "A", "research",
  "Operate on bytes grouped into dynamic patches instead of a fixed vocabulary.",
  [],
  "",
  [("G","Byte Latent Transformer","https://github.com/facebookresearch/blt",2024)]),
C("Tiny recursive reasoning models", "HRM, TRM", 2025, 2025, "A", "research",
  "Very small networks that loop over latent state, scoring well on puzzles like ARC-AGI with a few million parameters.",
  [],
  "",
  [("G","Hierarchical Reasoning Model","https://github.com/sapientinc/HRM",2025),
   ("G","Tiny Recursive Models","https://github.com/SamsungSAILMontreal/TinyRecursiveModels",2025)]),
C("Small language models", "SLM", 2024, 2026, "B", "cost open-source",
  "Compact models (about 0.5B to 30B) for on-device use, low latency and cheap agent subtasks.",
  [],
  "2026 mid-size open models (around 27B) deliver frontier-like coding on a single consumer GPU.",
  [("B","Hugging Face: SmolLM3","https://huggingface.co/blog/smollm3",2025),
   ("D","Apple Foundation Models framework","https://developer.apple.com/documentation/foundationmodels",2025)]),
C("Architecture overviews", "", 2025, 2026, "B", "",
  "Side-by-side walkthroughs of how current open models differ.",
  [],
  "",
  [("B","Raschka: The big LLM architecture comparison","https://magazine.sebastianraschka.com/p/the-big-llm-architecture-comparison",2025),
   ("B","Raschka: LLM research papers 2026","https://magazine.sebastianraschka.com/p/llm-research-papers-2026-part1",2026)]),
]),

# =====================================================================
dict(id="training", title="Training at Scale and Fine-Tuning",
intro="How models are pretrained across thousands of accelerators, and how practitioners adapt them cheaply afterwards.",
concepts=[
C("Parallelism strategies", "DP, FSDP, TP, PP, EP, CP", 2019, 2026, "A", "foundational",
  "Data, fully-sharded, tensor, pipeline, expert and context parallelism split models and data across devices; real runs combine several.",
  [],
  "",
  [("B","HF: The Ultra-Scale Playbook","https://huggingface.co/spaces/nanotron/ultrascale-playbook",2025),
   ("B","How to Scale Your Model (JAX)","https://jax-ml.github.io/scaling-book/",2025),
   ("G","torchtitan","https://github.com/pytorch/torchtitan",2024),
   ("G","Megatron-LM","https://github.com/NVIDIA/Megatron-LM",2019),
   ("G","DeepSpeed","https://github.com/deepspeedai/DeepSpeed",2020)]),
C("Scaling laws", "", 2020, 2026, "I", "foundational",
  "Empirical power laws relating loss to parameters, data and compute; now also studied for RL and test-time compute.",
  [],
  "",
  [("P","Chinchilla","https://arxiv.org/abs/2203.15556",2022),
   ("D","Epoch AI data","https://epoch.ai/data",2022)]),
C("Muon and modern optimizers", "", 2024, 2026, "A", "research",
  "Muon orthogonalises momentum updates for matrix parameters and trains faster than AdamW at scale.",
  [],
  "Adopted in frontier open models including Kimi K2 and DeepSeek V4.",
  [("B","Keller Jordan: Muon","https://kellerjordan.github.io/posts/muon/",2024),
   ("G","Kimi K2","https://github.com/MoonshotAI/Kimi-K2",2025),
   ("G","modded-nanogpt","https://github.com/KellerJordan/modded-nanogpt",2024)]),
C("Data curation and synthetic data", "", 2023, 2026, "I", "",
  "Classifier filtering, deduplication, and synthetic textbooks, reasoning traces and agent trajectories.",
  [],
  "DeepSeek V4 pretrained on 32T+ tokens, more than double V3's corpus.",
  [("B","FineWeb","https://huggingface.co/spaces/HuggingFaceFW/blogpost-fineweb-v1",2024),
   ("B","Cosmopedia","https://huggingface.co/blog/cosmopedia",2024)]),
C("Mid-training", "", 2024, 2026, "I", "",
  "A stage between pretraining and post-training that shifts the mix toward code, math, long context and reasoning.",
  [],
  "",
  [("D","Allen AI OLMo","https://allenai.org/olmo",2024)]),
C("LoRA and parameter-efficient fine-tuning", "PEFT, LoRA, QLoRA", 2021, 2025, "I", "cost",
  "Train small low-rank adapters instead of all weights; QLoRA does it on a 4-bit base.",
  [],
  "",
  [("P","LoRA","https://arxiv.org/abs/2106.09685",2021),
   ("P","QLoRA","https://arxiv.org/abs/2305.14314",2023),
   ("B","Thinking Machines: LoRA without regret","https://thinkingmachines.ai/blog/lora/",2025),
   ("G","HF PEFT","https://github.com/huggingface/peft",2023)]),
C("Fine-tuning toolkits and APIs", "", 2023, 2026, "B", "open-source",
  "Tools that make SFT, DPO and RL fine-tuning accessible on one GPU or as a managed API.",
  [],
  "",
  [("G","Unsloth","https://github.com/unslothai/unsloth",2023),
   ("G","Axolotl","https://github.com/axolotl-ai-cloud/axolotl",2023),
   ("G","LLaMA-Factory","https://github.com/hiyouga/LLaMA-Factory",2023),
   ("D","Tinker","https://thinkingmachines.ai/tinker/",2025)]),
C("Model merging", "", 2023, 2025, "I", "",
  "Combining weights of several fine-tunes (SLERP, TIES, DARE) without further training.",
  [],
  "",
  [("G","mergekit","https://github.com/arcee-ai/mergekit",2023)]),
C("Decentralized training", "DiLoCo", 2023, 2026, "A", "research",
  "Training across loosely connected clusters that synchronise rarely.",
  [],
  "",
  [("P","DiLoCo","https://arxiv.org/abs/2311.08105",2023),
   ("G","prime-rl","https://github.com/PrimeIntellect-ai/prime-rl",2025)]),
C("Build-it-yourself references", "", 2023, 2026, "B", "open-source",
  "Minimal end-to-end codebases for learning how chat models are trained.",
  [],
  "",
  [("G","nanochat","https://github.com/karpathy/nanochat",2025),
   ("D","Stanford CS336","https://stanford-cs336.github.io",2025)]),
]),
]
