from common import C

PART3 = [
# =====================================================================
dict(id="inference", title="Inference and Serving",
intro="Serving cost now rivals training cost. These techniques decide tokens per second, latency and price.",
concepts=[
C("Inference engines", "", 2023, 2026, "B", "open-source production",
  "Servers that batch requests, manage the KV cache and run optimised kernels.",
  [],
  "vLLM and SGLang lead open serving; llama.cpp, Ollama and MLX dominate local use.",
  [("G","vLLM","https://github.com/vllm-project/vllm",2023),
   ("G","SGLang","https://github.com/sgl-project/sglang",2024),
   ("G","TensorRT-LLM","https://github.com/NVIDIA/TensorRT-LLM",2023),
   ("G","llama.cpp","https://github.com/ggml-org/llama.cpp",2023),
   ("G","Ollama","https://github.com/ollama/ollama",2023),
   ("G","MLX","https://github.com/ml-explore/mlx",2023)]),
C("KV cache and PagedAttention", "", 2023, 2025, "I", "foundational",
  "Keys and values of past tokens are cached; PagedAttention stores them in fixed pages like virtual memory.",
  [],
  "",
  [("P","PagedAttention","https://arxiv.org/abs/2309.06180",2023)]),
C("Continuous batching and prefix caching", "", 2022, 2025, "I", "cost",
  "Add and remove requests every step, and share cached prefixes (radix trees) across requests.",
  [],
  "",
  [("G","SGLang (RadixAttention)","https://github.com/sgl-project/sglang",2024)]),
C("Prefill/decode disaggregation", "PD disaggregation", 2024, 2026, "A", "production cost",
  "Run compute-bound prefill and memory-bound decode on separate pools, moving KV caches between them.",
  ["NVIDIA now builds separate rack types for prefill (CPX) and decode, scheduled together by Dynamo."],
  "Standard for large-scale serving of million-token contexts in 2026.",
  [("P","DistServe","https://arxiv.org/abs/2401.09670",2024),
   ("G","NVIDIA Dynamo","https://github.com/ai-dynamo/dynamo",2025),
   ("G","llm-d","https://github.com/llm-d/llm-d",2025),
   ("G","Mooncake","https://github.com/kvcache-ai/Mooncake",2024)]),
C("KV cache offloading", "", 2024, 2026, "A", "cost",
  "Spill KV caches to CPU memory, SSD or remote storage and reload them for later turns.",
  [],
  "",
  [("G","LMCache","https://github.com/LMCache/LMCache",2024)]),
C("Attention kernels", "FlashAttention", 2022, 2026, "A", "",
  "IO-aware fused attention kernels that avoid materialising the full attention matrix.",
  [],
  "",
  [("G","FlashAttention","https://github.com/Dao-AILab/flash-attention",2022),
   ("G","FlashInfer","https://github.com/flashinfer-ai/flashinfer",2023)]),
C("On-device and edge inference", "", 2023, 2026, "B", "cost",
  "Running models on phones, laptops and embedded hardware with quantised weights and NPU runtimes.",
  [],
  "",
  [("G","ExecuTorch","https://github.com/pytorch/executorch",2023),
   ("G","ONNX Runtime","https://github.com/microsoft/onnxruntime",2018)]),
C("LLM gateways and routers", "", 2023, 2026, "B", "production cost",
  "One API over many providers with fallbacks, budgets, caching and routing to cheaper models.",
  [],
  "",
  [("G","LiteLLM","https://github.com/BerriAI/litellm",2023),
   ("D","OpenRouter","https://openrouter.ai",2023)]),
C("Inference benchmarking", "", 2025, 2026, "I", "cost",
  "Measuring throughput, latency and cost per million tokens across hardware and software stacks.",
  [],
  "",
  [("G","InferenceMAX","https://github.com/InferenceMAX/InferenceMAX",2025),
   ("D","Artificial Analysis","https://artificialanalysis.ai",2024)]),
]),

# =====================================================================
dict(id="quant", title="Quantization and Number Formats",
intro="Lower precision is the cheapest speed-up available, and formats are increasingly standardised across vendors.",
concepts=[
C("Microscaling formats", "MX, MXFP8, MXFP4", 2023, 2026, "A", "open-standard cost",
  "An Open Compute Project standard: blocks of values share one scale, making 8-, 6- and 4-bit floats accurate enough for training and inference.",
  [],
  "",
  [("S","OCP Microscaling (MX) spec","https://www.opencompute.org/documents/ocp-microscaling-formats-mx-v1-0-spec-final-pdf",2023),
   ("P","Microscaling data formats","https://arxiv.org/abs/2310.10537",2023),
   ("G","openai/gpt-oss (MXFP4)","https://github.com/openai/gpt-oss",2025)]),
C("NVFP4", "", 2025, 2026, "A", "cost",
  "NVIDIA's 4-bit float with 16-value blocks and FP8 scales, native on Blackwell and Rubin.",
  [],
  "Rubin rack performance is quoted primarily in FP4 exaflops.",
  [("B","NVIDIA: Introducing NVFP4","https://developer.nvidia.com/blog/introducing-nvfp4-for-efficient-and-accurate-low-precision-inference/",2025)]),
C("FP8 training and inference", "E4M3, E5M2", 2022, 2026, "I", "",
  "Two 8-bit float layouts used for large-scale training and routine serving; KV caches are often stored in FP8.",
  [],
  "",
  [("P","FP8 formats for deep learning","https://arxiv.org/abs/2209.05433",2022)]),
C("Post-training quantization", "GPTQ, AWQ", 2022, 2025, "I", "cost",
  "Compress trained weights to 4 or 8 bits using calibration data.",
  [],
  "",
  [("P","GPTQ","https://arxiv.org/abs/2210.17323",2022),
   ("G","AWQ","https://github.com/mit-han-lab/llm-awq",2023),
   ("G","llm-compressor","https://github.com/vllm-project/llm-compressor",2024)]),
C("Quantization-aware training", "QAT", 2024, 2026, "A", "",
  "Simulate low precision during training so the model tolerates it.",
  [],
  "",
  [("G","torchao","https://github.com/pytorch/ao",2023)]),
C("GGUF and local model formats", "", 2023, 2026, "B", "open-source",
  "A single-file format for quantised models used by llama.cpp and local runners.",
  [],
  "",
  [("S","GGUF specification","https://github.com/ggml-org/ggml/blob/master/docs/gguf.md",2023),
   ("G","bitsandbytes","https://github.com/bitsandbytes-foundation/bitsandbytes",2021)]),
C("Ternary and 1-bit models", "BitNet", 2024, 2025, "A", "research",
  "Weights restricted to -1, 0, +1, trained from scratch for very cheap CPU inference.",
  [],
  "",
  [("G","Microsoft BitNet","https://github.com/microsoft/BitNet",2024)]),
]),

# =====================================================================
dict(id="hardware", title="AI Hardware, Interconnect and Datacenter Standards",
intro="The unit of compute is now a rack or pod. Open standards are forming to connect accelerators from different vendors.",
concepts=[
C("Rack-scale systems", "NVL72", 2024, 2026, "I", "",
  "Dozens of accelerators in one liquid-cooled rack joined by a single scale-up domain, behaving like one giant GPU.",
  ["GB200/GB300 NVL72 (Blackwell) dominated 2025.",
   "Vera Rubin NVL72 (72 Rubin GPUs, 36 Vera CPUs, NVLink 6, HBM4) began shipping to major clouds in 2026."],
  "NVIDIA quotes about 3.6 EF FP4 inference per Vera Rubin rack; Rubin Ultra (Kyber rack) is planned for H2 2027.",
  [("D","NVIDIA GB200 NVL72","https://www.nvidia.com/en-us/data-center/gb200-nvl72/",2024),
   ("B","ServeTheHome: Rubin platform at CES 2026","https://www.servethehome.com/nvidia-launches-next-generation-rubin-ai-compute-platform-at-ces-2026/",2026),
   ("B","DCD: Vera Rubin superchip","https://www.datacenterdynamics.com/en/news/nvidia-announces-vera-rubin-superchip-for-late-2026/",2026)]),
C("AMD Helios and Open Rack Wide", "MI455X", 2026, 2026, "I", "open-standard",
  "AMD's rack-scale platform built on the Open Rack Wide standard co-submitted with Meta to OCP, pairing MI455X GPUs (432 GB HBM4 each) with EPYC Venice CPUs.",
  ["Competes on memory capacity rather than raw FLOPs.",
   "Large 2026 deployments announced with OpenAI and Oracle."],
  "",
  [("D","AMD Instinct","https://www.amd.com/en/products/accelerators/instinct.html",2023),
   ("B","GPU Insights: Rubin vs Helios","https://gpuinsights.net/nvidia-rubin-vs-amd-helios-mi450-2026/",2026)]),
C("Scale-up vs. scale-out networking", "", 2024, 2026, "I", "foundational",
  "Scale-up links accelerators inside a pod with memory-semantic, sub-microsecond links; scale-out connects pods over Ethernet or InfiniBand.",
  [],
  "",
  [("B","Synopsys: Ethernet standards for scale-up AI","https://www.synopsys.com/articles/ethernet-standards-scale-up-ai.html",2026)]),
C("UALink", "Ultra Accelerator Link", 2024, 2026, "I", "open-standard",
  "An open memory-semantic interconnect for pods of up to 1,024 accelerators, backed by AMD, Google, Microsoft, Meta, AWS and 100+ members.",
  ["UALink 200G 1.0 (April 2025); version 2.0 published April 2026.",
   "First UALink switches targeted late 2026."],
  "",
  [("S","UALink Consortium","https://ualinkconsortium.org",2024),
   ("D","UALink overview","https://en.wikipedia.org/wiki/UALink",2024),
   ("B","UALink white paper (2026)","https://ualinkconsortium.org/wp-content/uploads/2026/01/UALink_White_Paper_Publication_Candidate_FINAL_VERSION.pdf",2026)]),
C("ESUN and SUE", "Ethernet for Scale-Up Networking", 2025, 2026, "A", "open-standard",
  "An OCP workstream (October 2025) standardising Ethernet's lower layers for scale-up AI; Broadcom's SUE evolved into a transport that sits on top.",
  ["Backed by AMD, Arista, ARM, Broadcom, Cisco, HPE, Marvell, Meta, Microsoft, NVIDIA, OpenAI and Oracle."],
  "",
  [("B","Arista: The sun rises on scale-up Ethernet","https://blogs.arista.com/blog/the-sun-rises-on-scale-up-ethernet",2025),
   ("B","Synopsys: ESUN explained","https://www.synopsys.com/blogs/chip-design/esun-ethernet-ai-scale-up-networking.html",2026),
   ("B","650 Group: Ethernet in scale-up","https://650group.com/blog/in-the-ai-era-ethernet-set-to-surge-in-scale-out-and-ramp-in-scale-up/",2026)]),
C("Ultra Ethernet", "UEC", 2023, 2026, "A", "open-standard",
  "A consortium spec modernising Ethernet transport (packet spraying, congestion control, telemetry) for scale-out AI.",
  [],
  "",
  [("S","Ultra Ethernet Consortium","https://ultraethernet.org",2023)]),
C("NVLink and NVLink Fusion", "", 2016, 2026, "I", "",
  "NVIDIA's proprietary scale-up fabric, licensed through NVLink Fusion to third-party CPUs and accelerators.",
  [],
  "NVLink 6 ships with Rubin.",
  [("D","NVLink Fusion","https://www.nvidia.com/en-us/data-center/nvlink-fusion/",2025)]),
C("CXL, PCIe and UCIe", "", 2019, 2026, "A", "open-standard",
  "Coherent memory pooling (CXL), host I/O (PCIe) and chiplet die-to-die links (UCIe).",
  [],
  "",
  [("S","CXL Consortium","https://computeexpresslink.org",2019),
   ("S","PCI-SIG","https://pcisig.com",1992),
   ("S","UCIe","https://www.uciexpress.org",2022)]),
C("High-bandwidth memory", "HBM3E, HBM4", 2013, 2026, "I", "",
  "Stacked DRAM beside the accelerator; capacity and bandwidth usually limit decoding speed more than FLOPs.",
  [],
  "HBM4 arrived in 2026 with Rubin and MI455X; HBM4E is on 2027 roadmaps.",
  [("D","High Bandwidth Memory overview","https://en.wikipedia.org/wiki/High_Bandwidth_Memory",2013)]),
C("Advanced packaging", "CoWoS", 2012, 2026, "A", "",
  "2.5D/3D packaging that places compute dies and HBM on a shared interposer; a recurring supply bottleneck.",
  [],
  "",
  [("D","TSMC CoWoS","https://3dfabric.tsmc.com/english/dedicatedFoundry/technology/cowos.htm",2012)]),
C("Co-packaged optics", "CPO", 2025, 2026, "A", "",
  "Optical transceivers moved into the switch package to cut power and raise bandwidth.",
  [],
  "",
  [("D","NVIDIA silicon photonics","https://www.nvidia.com/en-us/networking/products/silicon-photonics/",2025)]),
C("Custom accelerators", "TPU, Trainium, MTIA", 2016, 2026, "I", "",
  "Hyperscaler and challenger chips competing with GPUs, often optimised for inference.",
  [],
  "",
  [("B","Google: Ironwood TPU","https://blog.google/products/google-cloud/ironwood-tpu-age-of-inference/",2025),
   ("D","AWS Trainium","https://aws.amazon.com/ai/machine-learning/trainium/",2020),
   ("D","Cerebras","https://www.cerebras.ai",2016),
   ("D","Groq","https://groq.com",2016)]),
C("AI factories, power and cooling", "800 VDC", 2024, 2026, "I", "",
  "Gigawatt-scale datacenters with direct liquid cooling and higher-voltage DC power; power is now a primary constraint.",
  [],
  "",
  [("B","NVIDIA: 800 V HVDC architecture","https://developer.nvidia.com/blog/nvidia-800-v-hvdc-architecture-will-power-the-next-generation-of-ai-factories/",2025),
   ("S","Open Compute Project","https://www.opencompute.org",2011),
   ("B","OpenAI: Stargate","https://openai.com/index/announcing-the-stargate-project/",2025)]),
C("Kernel languages and compilers", "Triton, CUTLASS, ROCm, XLA", 2019, 2026, "A", "open-source",
  "Tools for writing fast accelerator code without raw CUDA, and portable compilers.",
  [],
  "",
  [("G","Triton","https://github.com/triton-lang/triton",2019),
   ("G","CUTLASS / CuTe","https://github.com/NVIDIA/cutlass",2017),
   ("G","ThunderKittens","https://github.com/HazyResearch/ThunderKittens",2024),
   ("G","TileLang","https://github.com/tile-ai/tilelang",2025),
   ("G","ROCm","https://github.com/ROCm/ROCm",2016),
   ("G","OpenXLA","https://github.com/openxla/xla",2022),
   ("G","Modular (Mojo, MAX)","https://github.com/modular/modular",2023)]),
C("Collective communication", "NCCL", 2016, 2026, "A", "",
  "Libraries for all-reduce, all-gather and all-to-all across GPUs.",
  [],
  "",
  [("G","NCCL","https://github.com/NVIDIA/nccl",2016),
   ("G","DeepEP","https://github.com/deepseek-ai/DeepEP",2025)]),
C("Model interchange formats", "ONNX, safetensors", 2017, 2025, "B", "open-standard",
  "Standard, safe formats for moving models between frameworks; safetensors avoids pickle code execution.",
  [],
  "",
  [("G","ONNX","https://github.com/onnx/onnx",2017),
   ("G","safetensors","https://github.com/huggingface/safetensors",2022)]),
C("Hardware benchmarks", "MLPerf", 2018, 2026, "B", "",
  "Industry-standard training and inference benchmarks.",
  [],
  "",
  [("D","MLCommons benchmarks","https://mlcommons.org/benchmarks/",2018),
   ("D","Epoch AI: ML hardware data","https://epoch.ai/data/machine-learning-hardware",2023)]),
]),

# =====================================================================
dict(id="vlm", title="Vision-Language and Multimodal Models",
intro="VLMs join a vision encoder to a language model so one system can read images, documents, screens and video. Omni models add audio in and out.",
concepts=[
C("VLM architecture", "", 2023, 2026, "B", "foundational",
  "A vision encoder turns image patches into tokens, a projector maps them into the LLM space, and the LLM reasons over both. Native multimodal models train everything jointly.",
  [],
  "",
  [("B","Hugging Face: Vision language models 2025","https://huggingface.co/blog/vlms-2025",2025),
   ("G","LLaVA","https://github.com/haotian-liu/LLaVA",2023),
   ("P","SigLIP 2","https://arxiv.org/abs/2502.14786",2025)]),
C("Open VLM families", "", 2024, 2026, "B", "open-source",
  "Open-weight VLMs for images, documents and video, including small on-device models.",
  [],
  "Closed models (Gemini, GPT, Claude) still top leaderboards; Qwen-VL, InternVL and Gemma 4 (April 2026, vision in every size) lead open options.",
  [("G","Qwen3-VL","https://github.com/QwenLM/Qwen3-VL",2025),
   ("G","InternVL","https://github.com/OpenGVLab/InternVL",2023),
   ("B","SmolVLM","https://huggingface.co/blog/smolvlm",2024),
   ("B","BentoML: Open VLM guide","https://www.bentoml.com/blog/multimodal-ai-a-guide-to-open-source-vision-language-models",2026)]),
C("Native and dynamic resolution", "", 2023, 2025, "I", "",
  "Handle images at their original aspect ratio and resolution by tiling or packing variable patch counts.",
  [],
  "",
  [("P","NaViT","https://arxiv.org/abs/2307.06304",2023)]),
C("Thinking with images", "", 2025, 2026, "I", "",
  "Reasoning models that crop, zoom and transform images inside their chain of thought.",
  [],
  "",
  [("B","OpenAI: Thinking with images","https://openai.com/index/thinking-with-images/",2025)]),
C("Document AI and VLM-based OCR", "", 2024, 2026, "I", "production open-source",
  "VLMs that convert PDFs and scans into clean Markdown, tables and structure.",
  [],
  "",
  [("G","DeepSeek-OCR","https://github.com/deepseek-ai/DeepSeek-OCR",2025),
   ("G","olmOCR","https://github.com/allenai/olmocr",2025),
   ("G","Docling","https://github.com/docling-project/docling",2024),
   ("G","PaddleOCR","https://github.com/PaddlePaddle/PaddleOCR",2020)]),
C("Visual document retrieval", "ColPali", 2024, 2025, "I", "",
  "Embed page images directly and retrieve with late interaction, skipping OCR.",
  [],
  "",
  [("G","ColPali","https://github.com/illuin-tech/colpali",2024)]),
C("GUI grounding agents", "", 2024, 2026, "A", "",
  "VLMs trained to locate UI elements and act on screens.",
  [],
  "",
  [("G","UI-TARS","https://github.com/bytedance/UI-TARS",2025),
   ("G","OmniParser","https://github.com/microsoft/OmniParser",2024)]),
C("Omni and speech-to-speech models", "", 2024, 2026, "I", "",
  "Models that take and produce audio natively for low-latency voice agents.",
  [],
  "2026 omni models handle text, image, video and audio input with 1M-token windows.",
  [("G","Qwen3-Omni","https://github.com/QwenLM/Qwen3-Omni",2025),
   ("G","Moshi","https://github.com/kyutai-labs/moshi",2024),
   ("D","OpenAI Realtime API","https://platform.openai.com/docs/guides/realtime",2024),
   ("G","Pipecat","https://github.com/pipecat-ai/pipecat",2024),
   ("G","LiveKit Agents","https://github.com/livekit/agents",2024),
   ("G","Whisper","https://github.com/openai/whisper",2022)]),
C("Native image generation and editing", "", 2025, 2026, "B", "",
  "LLMs that generate and edit images in the same model with strong text rendering and instruction-following.",
  [],
  "",
  [("B","OpenAI: 4o image generation","https://openai.com/index/introducing-4o-image-generation/",2025),
   ("B","Google: Gemini 2.5 Flash Image","https://developers.googleblog.com/en/introducing-gemini-2-5-flash-image/",2025)]),
C("Multimodal evaluation", "", 2023, 2026, "I", "",
  "Benchmarks and harnesses for reasoning, charts, documents and video.",
  [],
  "",
  [("D","MMMU","https://mmmu-benchmark.github.io",2023),
   ("G","VLMEvalKit","https://github.com/open-compass/VLMEvalKit",2023),
   ("G","lmms-eval","https://github.com/EvolvingLMMs-Lab/lmms-eval",2024)]),
]),
]
