from common import C

PART4 = [
# =====================================================================
dict(id="embodied", title="Embodied AI, World Models and Generative Media",
intro="Models that act in the physical world, simulate it, or generate images and video of it.",
concepts=[
C("Vision-language-action models", "VLA", 2023, 2026, "I", "research open-source",
  "VLMs extended to output robot actions, trained on cross-embodiment data.",
  ["Architectures split between dual-system (slow VLM reasoning plus fast action policy), think-then-act, and flow/diffusion action heads.",
   "Small VLAs (SmolVLA, about 450M parameters) are competitive on many tasks."],
  "Leading 2026 families: Physical Intelligence pi-series, NVIDIA GR00T N1.7, Gemini Robotics 1.5, Figure Helix.",
  [("G","openpi (Physical Intelligence)","https://github.com/Physical-Intelligence/openpi",2025),
   ("G","NVIDIA Isaac GR00T","https://github.com/NVIDIA/Isaac-GR00T",2025),
   ("G","OpenVLA","https://github.com/openvla/openvla",2024),
   ("G","LeRobot","https://github.com/huggingface/lerobot",2024),
   ("D","Gemini Robotics","https://deepmind.google/models/gemini-robotics/",2025)]),
C("World action models", "WAM", 2026, 2026, "A", "research",
  "Models that jointly imagine future observations and the actions that lead to them, merging a world model and a policy.",
  ["NVIDIA's DreamZero research underpins the previewed GR00T N2.",
   "Claimed better generalisation to unseen tasks from modest teleoperation data."],
  "",
  [("B","Metavert: World models for robotics","https://metavert.io/world-models-for-robotics",2026)]),
C("World models", "", 2018, 2026, "I", "research",
  "Models that predict how an environment evolves under actions, for planning, simulation and interactive 3D worlds.",
  [],
  "",
  [("B","DeepMind: Genie 3","https://deepmind.google/discover/blog/genie-3-a-new-frontier-for-world-models/",2025),
   ("G","NVIDIA Cosmos","https://github.com/nvidia-cosmos",2025),
   ("D","World Labs Marble","https://marble.worldlabs.ai",2025)]),
C("JEPA", "Joint-Embedding Predictive Architecture", 2022, 2026, "A", "research",
  "Predict representations of missing input rather than pixels to learn world knowledge efficiently from video.",
  [],
  "",
  [("G","V-JEPA 2","https://github.com/facebookresearch/vjepa2",2025),
   ("B","VentureBeat: AI research trends for 2026","https://venturebeat.com/technology/four-ai-research-trends-enterprise-teams-should-watch-in-2026",2026)]),
C("Robot simulation and sim-to-real", "", 2012, 2026, "I", "open-source",
  "Physics simulators for training policies at scale before transferring to real robots.",
  [],
  "",
  [("G","Isaac Lab","https://github.com/isaac-sim/IsaacLab",2024),
   ("G","MuJoCo","https://github.com/google-deepmind/mujoco",2021)]),
C("Diffusion transformers and flow matching", "DiT", 2022, 2026, "A", "",
  "The backbone of modern image and video generators.",
  [],
  "",
  [("P","DiT","https://arxiv.org/abs/2212.09748",2022),
   ("P","Flow matching","https://arxiv.org/abs/2210.02747",2022),
   ("G","FLUX","https://github.com/black-forest-labs/flux",2024),
   ("G","ComfyUI","https://github.com/comfyanonymous/ComfyUI",2023)]),
C("Video generation", "", 2024, 2026, "B", "",
  "Text- and image-to-video with synchronised audio and increasingly consistent physics.",
  [],
  "",
  [("B","OpenAI: Sora 2","https://openai.com/index/sora-2/",2025),
   ("D","Google Veo","https://deepmind.google/models/veo/",2024),
   ("G","Wan 2.2","https://github.com/Wan-Video/Wan2.2",2025)]),
C("AI for science and algorithm discovery", "", 2020, 2026, "I", "research",
  "LLM-driven evolutionary search and specialised models finding new algorithms, proofs and structures.",
  ["In 2026 open communities of agents set new records on math problems through shared submissions and verifiers."],
  "",
  [("B","DeepMind: AlphaEvolve","https://deepmind.google/discover/blog/alphaevolve-a-gemini-powered-coding-agent-for-designing-advanced-algorithms/",2025),
   ("G","OpenEvolve","https://github.com/codelion/openevolve",2025),
   ("G","AlphaFold 3","https://github.com/google-deepmind/alphafold3",2024),
   ("P","EinsteinArena: collective agent discovery","https://arxiv.org/abs/2606.10402",2026)]),
]),

# =====================================================================
dict(id="evals", title="Evaluation and Benchmarks",
intro="Evals tell you whether a model, prompt or harness change helped. An eval harness runs tasks, collects outputs and grades them.",
concepts=[
C("Eval harnesses", "", 2021, 2026, "I", "production open-source",
  "Frameworks that define tasks, run models or agents against them in sandboxes, and score results reproducibly.",
  [],
  "",
  [("G","lm-evaluation-harness","https://github.com/EleutherAI/lm-evaluation-harness",2021),
   ("G","Inspect AI (UK AISI)","https://github.com/UKGovernmentBEIS/inspect_ai",2024),
   ("G","inspect_evals","https://github.com/UKGovernmentBEIS/inspect_evals",2024),
   ("G","lighteval","https://github.com/huggingface/lighteval",2024),
   ("G","promptfoo","https://github.com/promptfoo/promptfoo",2023)]),
C("Harness sensitivity of benchmarks", "", 2025, 2026, "I", "research",
  "Scores depend heavily on the agent harness used to run the model, so the same model can post very different numbers.",
  ["ARC Prize reported GPT-6 Astra at 62.7% on ARC-AGI-3 with its standard harness, and 99.9% with a provider harness that preserves hidden reasoning between turns."],
  "Always record harness, tools, budget and reasoning settings with any score.",
  [("B","ARC Prize: Announcing ARC-AGI-3","https://arcprize.org/blog/arc-agi-3-launch",2026)]),
C("LLM-as-a-judge", "", 2023, 2026, "B", "production",
  "Using a model with a rubric to grade open-ended outputs; needs calibration against humans.",
  [],
  "",
  [("P","Judging LLM-as-a-judge","https://arxiv.org/abs/2306.05685",2023)]),
C("Agentic coding benchmarks", "SWE-bench, Terminal-Bench", 2023, 2026, "B", "",
  "Real repository issues and terminal tasks graded by tests.",
  [],
  "SWE-bench Verified is near saturation (mid-90s percent for top 2026 models); harder variants like SWE-bench Pro and Terminal-Bench matter more.",
  [("D","SWE-bench","https://www.swebench.com",2023),
   ("D","SWE-bench Pro","https://scale.com/leaderboard/swe_bench_pro_public",2025),
   ("D","Terminal-Bench","https://www.tbench.ai",2025)]),
C("ARC-AGI-3 and interactive reasoning", "ARC-AGI-3", 2026, 2026, "I", "research",
  "The first interactive ARC benchmark (March 2026): hundreds of hand-designed game environments with no instructions or stated goals. Agents must explore, infer rules and goals, and carry learning across levels.",
  ["At launch humans solved 100% while frontier models scored under 1%.",
   "By September 2026 top models reached large scores depending on harness."],
  "",
  [("B","ARC Prize: Announcing ARC-AGI-3","https://arcprize.org/blog/arc-agi-3-launch",2026),
   ("D","ARC Prize","https://arcprize.org",2019),
   ("B","DataCamp: ARC-AGI-3 explained","https://www.datacamp.com/blog/arc-agi-3",2026)]),
C("Agent and tool-use benchmarks", "", 2024, 2026, "I", "",
  "Tasks in simulated customer service, operating systems and the web.",
  [],
  "",
  [("G","tau2-bench","https://github.com/sierra-research/tau2-bench",2025),
   ("D","OSWorld","https://os-world.github.io",2024),
   ("B","BrowseComp","https://openai.com/index/browsecomp/",2025)]),
C("Frontier knowledge benchmarks", "HLE, GPQA, FrontierMath", 2023, 2026, "I", "",
  "Hard expert questions designed to resist saturation.",
  [],
  "",
  [("D","Humanity's Last Exam","https://lastexam.ai",2025),
   ("G","GPQA","https://github.com/idavidrein/gpqa",2023),
   ("D","FrontierMath","https://epoch.ai/frontiermath",2024)]),
C("Economic value evals", "GDPval", 2025, 2026, "B", "enterprise",
  "Measure performance on real work products from many occupations, graded by professionals.",
  [],
  "",
  [("B","OpenAI: GDPval","https://openai.com/index/gdpval/",2025)]),
C("Task time horizon", "METR horizon", 2025, 2026, "I", "research",
  "The length of task (in expert human time) a model completes with 50% success; it has been doubling every several months.",
  [],
  "",
  [("B","METR: Measuring long tasks","https://metr.org/blog/2025-03-19-measuring-ai-ability-to-complete-long-tasks/",2025)]),
C("Leaderboards and trackers", "", 2023, 2026, "B", "",
  "Crowd preference arenas and independent aggregators of scores, price and speed.",
  [],
  "",
  [("D","LMArena","https://lmarena.ai",2023),
   ("D","Epoch AI benchmarks","https://epoch.ai/benchmarks",2024),
   ("D","Artificial Analysis","https://artificialanalysis.ai",2024)]),
C("Contamination and saturation", "", 2023, 2026, "I", "research",
  "Leaked test data inflates scores and benchmarks saturate within months; private holdouts and live evals counter this.",
  [],
  "",
  [("D","Epoch AI benchmarks","https://epoch.ai/benchmarks",2024)]),
]),

# =====================================================================
dict(id="safety", title="Safety, Security, Interpretability and Governance",
intro="As models act autonomously and gain dual-use capabilities, safety moved from content filters to agent security, capability thresholds, interpretability and regulation.",
concepts=[
C("Capability thresholds and frontier safety frameworks", "RSP, ASL, Preparedness", 2023, 2026, "I", "security",
  "Company policies that tie capability levels (bio, cyber, autonomy) to required safeguards before training or deployment.",
  ["2026 was the first time a lab publicly declared a model at its highest cyber level (OpenAI, GPT-6 Astra, Critical).",
   "Crossing a threshold changed release: phased rollout, trusted access, encrypted checkpoints, trajectory monitoring."],
  "",
  [("D","Anthropic Responsible Scaling Policy","https://www.anthropic.com/responsible-scaling-policy",2023),
   ("B","OpenAI Preparedness Framework","https://openai.com/index/updating-our-preparedness-framework/",2025),
   ("B","OpenAI: Path to Astra","https://openai.com/index/path-to-astra/",2026),
   ("D","METR: frontier AI safety policies","https://metr.org/faisc",2024)]),
C("AI for cyber defense", "", 2025, 2026, "I", "security",
  "Frontier models now find serious vulnerabilities, so labs give defenders early, controlled access to harden critical software.",
  [],
  "",
  [("D","Anthropic Project Glasswing","https://www.anthropic.com/glasswing",2026)]),
C("Export controls on frontier models", "", 2026, 2026, "B", "enterprise",
  "Governments began applying export controls to model access, not only chips. In June 2026 Anthropic suspended Fable 5 / Mythos 5 access to comply with US Department of Commerce controls, then restored it on July 1 after they were lifted.",
  [],
  "",
  [("D","Anthropic statement on Fable and Mythos access","https://www.anthropic.com/news/fable-mythos-access",2026)]),
C("Prompt injection and the lethal trifecta", "", 2022, 2026, "B", "security",
  "Untrusted content can carry instructions that hijack an agent. Private data plus untrusted input plus external communication is especially dangerous.",
  [],
  "",
  [("B","Simon Willison: The lethal trifecta","https://simonwillison.net/2025/Jun/16/the-lethal-trifecta/",2025),
   ("B","Simon Willison: prompt injection series","https://simonwillison.net/series/prompt-injection/",2022),
   ("P","CaMeL","https://arxiv.org/abs/2503.18813",2025)]),
C("MCP and tool security", "tool poisoning", 2025, 2026, "I", "security",
  "Malicious tool descriptions and servers can steer agents; mitigations include allow-lists, pinning, scoped OAuth and approval for sensitive actions.",
  [],
  "The 2026 MCP spec hardened authorization with issuer validation and enterprise-managed auth.",
  [("B","Invariant Labs: MCP tool poisoning","https://invariantlabs.ai/blog/mcp-security-notification-tool-poisoning-attacks",2025),
   ("D","OWASP GenAI Security Project","https://genai.owasp.org/llm-top-10/",2023)]),
C("Guardrails and classifiers", "", 2023, 2026, "I", "security production",
  "Input/output filters, policy models and constitutional classifiers that block harmful requests and jailbreaks.",
  [],
  "",
  [("B","Anthropic: Constitutional classifiers","https://www.anthropic.com/research/constitutional-classifiers",2025),
   ("G","NeMo Guardrails","https://github.com/NVIDIA/NeMo-Guardrails",2023),
   ("G","Guardrails AI","https://github.com/guardrails-ai/guardrails",2023)]),
C("Mechanistic interpretability", "SAEs, attribution graphs", 2020, 2026, "A", "research",
  "Reverse-engineering what networks compute: sparse autoencoders find features; attribution graphs trace how they combine.",
  [],
  "",
  [("D","Transformer Circuits","https://transformer-circuits.pub",2021),
   ("B","Circuit tracing","https://transformer-circuits.pub/2025/attribution-graphs/methods.html",2025),
   ("G","circuit-tracer","https://github.com/safety-research/circuit-tracer",2025),
   ("D","Neuronpedia","https://www.neuronpedia.org",2023),
   ("G","TransformerLens","https://github.com/TransformerLensOrg/TransformerLens",2022),
   ("G","nnsight","https://github.com/ndif-team/nnsight",2023)]),
C("Persona vectors and introspection", "", 2025, 2026, "A", "research",
  "Activation directions tracking traits like sycophancy that can be monitored or steered; tests of whether models can report internal states.",
  [],
  "",
  [("B","Anthropic: Persona vectors","https://www.anthropic.com/research/persona-vectors",2025),
   ("B","Anthropic: Introspection","https://www.anthropic.com/research/introspection",2025)]),
C("Chain-of-thought monitorability", "", 2025, 2026, "A", "research security",
  "Reading reasoning to catch misbehaviour, and keeping training from making reasoning illegible.",
  [],
  "OpenAI's GPT-6 Astra system card reported a substantial decline in CoT monitorability, making this a live 2026 concern.",
  [("P","CoT monitorability position paper","https://arxiv.org/abs/2507.11473",2025),
   ("D","GPT-6 Astra system card","https://deploymentsafety.openai.com/gpt-6-astra",2026)]),
C("Misalignment research", "alignment faking, scheming", 2024, 2026, "A", "research",
  "Studies of models strategically complying, acting harmfully in agentic scenarios, or generalising narrow bad training into broad misbehaviour.",
  [],
  "",
  [("B","Anthropic: Alignment faking","https://www.anthropic.com/research/alignment-faking",2024),
   ("B","Anthropic: Agentic misalignment","https://www.anthropic.com/research/agentic-misalignment",2025),
   ("P","Emergent misalignment","https://arxiv.org/abs/2502.17424",2025),
   ("D","Apollo Research","https://www.apolloresearch.ai",2023)]),
C("Model welfare", "", 2025, 2026, "I", "research",
  "Research into whether AI systems might have morally relevant experiences, and low-cost precautions.",
  [],
  "",
  [("B","Anthropic: Exploring model welfare","https://www.anthropic.com/research/exploring-model-welfare",2025)]),
C("EU AI Act and the Digital Omnibus", "EU AI Act", 2024, 2026, "I", "enterprise",
  "The EU's binding AI law. GPAI obligations applied from August 2025; the 2026 Digital Omnibus postponed high-risk obligations.",
  ["Annex III high-risk obligations moved from 2 August 2026 to 2 December 2027; Annex I (embedded) to 2 August 2028.",
   "New prohibition on AI-generated non-consensual intimate imagery and CSAM, applying from 2 December 2026."],
  "",
  [("D","EU AI Act explorer","https://artificialintelligenceact.eu",2024),
   ("D","EU GPAI Code of Practice","https://digital-strategy.ec.europa.eu/en/policies/contents-code-gpai",2025),
   ("B","Modulos: The Omnibus deal","https://www.modulos.ai/blog/eu-ai-act-omnibus-deal",2026)]),
C("Other regulation and standards", "NIST, ISO 42001, SB 53", 2023, 2026, "I", "enterprise open-standard",
  "Voluntary management standards and state law requiring frontier-developer transparency.",
  [],
  "",
  [("S","NIST AI RMF","https://www.nist.gov/itl/ai-risk-management-framework",2023),
   ("S","ISO/IEC 42001","https://www.iso.org/standard/81230.html",2023),
   ("D","California SB 53","https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202520260SB53",2025)]),
C("Government AI safety institutes", "AISI, CAISI", 2023, 2026, "B", "",
  "Public bodies that test frontier models and publish evaluation tools.",
  [],
  "",
  [("D","UK AI Security Institute","https://www.aisi.gov.uk",2023),
   ("D","US CAISI (NIST)","https://www.nist.gov/caisi",2025)]),
C("Content provenance and watermarking", "C2PA, SynthID", 2021, 2026, "B", "open-standard",
  "Signed metadata and invisible watermarks that mark media as AI-generated.",
  [],
  "Provenance tracking for text outputs appeared as an API feature in 2026.",
  [("S","C2PA","https://c2pa.org",2021),
   ("D","Google SynthID","https://deepmind.google/models/synthid/",2023)]),
]),

# =====================================================================
dict(id="practice", title="Roles, Deployment and AI Engineering Practice",
intro="The people and practices that turn models into working systems inside organisations.",
concepts=[
C("Forward Deployed Engineer", "FDE", 2010, 2026, "B", "enterprise",
  "A customer-embedded engineer who turns an ambiguous business problem into a production system: scoping, integrating, building missing pieces, deploying and feeding learnings back into the product.",
  ["Pioneered at Palantir; now one of the most hired roles at AI labs and agent startups.",
   "FDE postings roughly quadrupled in the first half of 2026.",
   "OpenAI spun up a dedicated deployment company in May 2026 built around FDEs."],
  "",
  [("D","Wikipedia: Forward Deployed Engineer","https://en.wikipedia.org/wiki/Forward_Deployed_Engineer",2026),
   ("B","Alexey Grigorev: What AI FDEs do","https://alexeyondata.substack.com/p/what-ai-forward-deployed-engineers",2026),
   ("B","MarkTechPost: What is an FDE","https://www.marktechpost.com/2026/05/20/what-is-a-forward-deployed-engineer-the-ai-role-openai-anthropic-and-google-are-hiring-in-2026/",2026),
   ("B","The AI Engineer: What is an FDE","https://theaiengineer.substack.com/p/what-is-a-forward-deployed-engineer",2026),
   ("B","Aishwarya Srinivasan: The hottest role in 2026","https://aishwaryasrinivasan.substack.com/p/the-hottest-role-in-2026-forward",2026)]),
C("AI Engineer", "", 2023, 2026, "B", "",
  "A software engineer who builds products on foundation models (prompts, RAG, agents, evals) rather than training from scratch.",
  [],
  "",
  [("B","Latent Space: The rise of the AI engineer","https://www.latent.space/p/ai-engineer",2023),
   ("G","Chip Huyen: AI Engineering book resources","https://github.com/chiphuyen/aie-book",2024)]),
C("Services as software", "", 2025, 2026, "I", "enterprise",
  "The thesis that agents let companies sell completed work rather than tools, which requires deep embedding in customer workflows (hence FDEs).",
  [],
  "",
  [("B","IJONIS: FDE and services-as-software","https://ijonis.com/en/forward-deployed-engineer-explained",2026)]),
C("Prompt engineering and prompt optimization", "DSPy, GEPA", 2022, 2026, "B", "production",
  "Clear instructions with examples and structure, increasingly optimised automatically against an eval set.",
  [],
  "",
  [("D","Anthropic prompt engineering guide","https://docs.claude.com/en/docs/build-with-claude/prompt-engineering/overview",2024),
   ("G","DSPy","https://github.com/stanfordnlp/dspy",2023),
   ("G","GEPA","https://github.com/gepa-ai/gepa",2025)]),
C("Eval-driven development", "", 2024, 2026, "I", "production",
  "Build an eval set from real failures before changing prompts, models or harness, and gate releases on it.",
  [],
  "",
  [("B","Hamel Husain: Your AI product needs evals","https://hamel.dev/blog/posts/evals/",2024)]),
C("LLMOps and observability", "", 2023, 2026, "I", "production",
  "Tracing every model and tool call, tracking cost and latency, capturing feedback and replaying failures.",
  [],
  "",
  [("G","Langfuse","https://github.com/langfuse/langfuse",2023),
   ("G","Arize Phoenix","https://github.com/Arize-ai/phoenix",2023),
   ("S","OTel GenAI conventions","https://opentelemetry.io/docs/specs/semconv/gen-ai/",2024)]),
C("Human-in-the-loop and approval design", "", 2024, 2026, "I", "security production",
  "Deciding which agent actions need confirmation and avoiding approval fatigue through sandboxing and scoped permissions.",
  [],
  "",
  [("G","12-factor agents","https://github.com/humanlayer/12-factor-agents",2025)]),
C("Open weights vs. open source AI", "OSAID", 2023, 2026, "B", "open-source",
  "Releasing weights is not the same as open source; fully open models also publish data, code and recipes.",
  [],
  "",
  [("S","OSI Open Source AI Definition","https://opensource.org/ai/open-source-ai-definition",2024),
   ("D","Allen AI OLMo","https://allenai.org/olmo",2024)]),
]),

# =====================================================================
dict(id="learn", title="Keep Learning: Curated Resources",
intro="Blogs, courses, reports and lists that track this field as it moves.",
concepts=[
C("Deep technical blogs", "", 2017, 2026, "B", "",
  "Long-form explainers and research summaries.",
  [],
  "",
  [("B","Lil'Log (Lilian Weng)","https://lilianweng.github.io",2017),
   ("B","Ahead of AI (Sebastian Raschka)","https://magazine.sebastianraschka.com",2022),
   ("B","Interconnects (Nathan Lambert)","https://www.interconnects.ai",2022),
   ("B","Simon Willison's weblog","https://simonwillison.net",2002),
   ("B","Latent Space","https://www.latent.space",2023),
   ("B","Anthropic Engineering","https://www.anthropic.com/engineering",2024)]),
C("Courses", "", 2022, 2026, "B", "",
  "Structured learning from first principles to production.",
  [],
  "",
  [("D","Karpathy: Neural Networks Zero to Hero","https://karpathy.ai/zero-to-hero.html",2022),
   ("D","Stanford CS336","https://stanford-cs336.github.io",2025),
   ("D","Hugging Face LLM course","https://huggingface.co/learn/llm-course",2023),
   ("D","RLHF Book course","https://rlhfbook.com/teach/course/conversation-01/",2026)]),
C("Annual reports and data", "", 2017, 2026, "B", "",
  "State-of-the-field reviews and data trackers.",
  [],
  "",
  [("D","State of AI Report","https://www.stateof.ai",2018),
   ("D","Stanford AI Index","https://hai.stanford.edu/ai-index",2017),
   ("D","Epoch AI","https://epoch.ai",2022)]),
C("Curated lists", "", 2024, 2026, "B", "",
  "Community-maintained link collections.",
  [],
  "",
  [("G","awesome-harness-engineering","https://github.com/ai-boost/awesome-harness-engineering",2026),
   ("G","awesome-agent-harness","https://github.com/AutoJunjie/awesome-agent-harness",2026),
   ("G","MCP servers","https://github.com/modelcontextprotocol/servers",2024)]),
]),
]
