POINTS = {
# protocols
"Agentic AI Foundation": ["Neutral governance so no single vendor controls core agent standards.", "Hosts specs, reference implementations and working groups."],
"Agent Client Protocol": ["Editors act as clients; agents run as subprocesses speaking JSON-RPC.", "Lets one agent work in Zed, JetBrains, Neovim and others without per-editor plugins."],
"AG-UI": ["Streams typed events: text deltas, tool calls, state patches, human-input requests.", "Complements MCP (tools) and A2A (agents) on the user-facing side."],
"llms.txt": ["Plain Markdown with links and short descriptions.", "Often paired with .md versions of docs pages for clean agent reading."],
"OpenTelemetry GenAI conventions": ["Standard attributes for model name, token counts, prompts and tool calls.", "Supported by most LLMOps tools and agent SDKs."],
# coding
"Vibe coding": ["Useful for throwaway prototypes, personal tools and learning.", "Unreviewed code carries security and maintenance risk in production."],
"Spec-driven development": ["Typical flow: specify, plan, break into tasks, implement, verify.", "The spec doubles as durable context for future agent sessions."],
"Ralph loop": ["Progress lives in files and git, not in the context window.", "Works best with strong tests so each iteration can check its own work."],
"Hooks, plugins and slash commands": ["Hooks enforce rules deterministically (formatters, linters, blocked commands).", "Plugins make a team's setup installable in one step."],
"Parallel agents with git worktrees": ["Each agent gets its own branch and working directory, avoiding conflicts.", "The human shifts from typing to dispatching and reviewing."],
# context
"Context rot": ["Distractors and similar-but-wrong passages hurt more than raw length.", "Mitigate with retrieval, summarisation and subagents."],
"Compaction and context editing": ["Clear old tool outputs first; they are usually the largest and least useful.", "Keep decisions, open problems and file paths in the summary."],
"GraphRAG": ["Entity and relation extraction with an LLM, then community summaries.", "More expensive to index than vector RAG."],
"Embeddings, late interaction and Matryoshka": ["Choose embeddings by your domain and language, not only leaderboard rank.", "Rerankers usually give the biggest quality jump after the first retrieval."],
"Structured outputs and constrained decoding": ["Grammar engines compile schemas into token masks for near-zero overhead.", "Guarantees valid syntax, not correct content."],
# reasoning
"Reasoning models and test-time compute": ["Techniques: long chain-of-thought, self-verification, parallel sampling with voting.", "More thinking helps most on math, code and multi-step planning."],
"Thinking budgets, adaptive thinking and effort": ["Low effort for chat and simple tool calls; high for hard debugging or proofs.", "Interleaved thinking helps agents adjust after each tool result."],
"GRPO and its successors": ["Sample a group of answers per prompt; advantage = reward minus group mean.", "No critic network means less memory and simpler training."],
"RLHF, DPO and preference optimization": ["RLHF: SFT, then reward model, then PPO.", "DPO optimises the same objective in closed form from preference pairs."],
"Constitutional AI and model specs": ["The model critiques and revises its own outputs against principles.", "Published specs make intended behaviour inspectable."],
"Process reward models": ["Enable step-level search (beam search over reasoning steps).", "Expensive to label; often trained with automated step checks."],
"Reward hacking": ["Watch for tests being deleted, asserts weakened or outputs hard-coded.", "Defenses: held-out verifiers, monitoring, diverse environments."],
"Self-play and self-generated curricula": ["A proposer creates tasks near the solver's frontier.", "Verification (code execution, math checkers) keeps it grounded."],
# arch
"GQA and Multi-head Latent Attention": ["GQA: fewer KV heads than query heads.", "MLA: store a small latent, up-project at attention time; decoupled RoPE dims."],
"Hybrid linear-attention and state space models": ["Linear layers keep a fixed-size state instead of a growing KV cache.", "A few full-attention layers preserve precise recall."],
"Diffusion language models": ["Start from masked or noisy tokens and refine in parallel steps.", "Trade-offs: quality on long reasoning, variable-length output."],
"Multi-token prediction and speculative decoding": ["Draft models, extra prediction heads (MTP, Medusa, EAGLE) or n-gram lookup.", "Output distribution is unchanged when verification is exact."],
"Long-context methods": ["Train short, extend with RoPE scaling plus long-context fine-tuning.", "Needle tests are easy; multi-hop reasoning over long input is hard."],
"Attention sinks": ["Keep the first few tokens when using sliding-window caches.", "Some models add explicit sink parameters per head."],
"Tokenizer-free and byte-level models": ["Patch boundaries adapt to entropy, spending compute on hard bytes.", "Improves robustness on typos, code and rare scripts."],
"Tiny recursive reasoning models": ["Iterate a small network many times on its own latent answer.", "Shows depth-through-recursion can substitute for parameters on some tasks."],
"Small language models": ["Often distilled from large teachers.", "Good fits: routing, extraction, classification, on-device assistants."],
"Architecture overviews": ["Compare norms, attention type, expert counts, positional schemes.", "Read tech reports for data and training details that diagrams omit."],
# training
"Parallelism strategies": ["FSDP shards parameters, gradients and optimizer state.", "Tensor and expert parallelism need fast scale-up links; pipeline tolerates slower links."],
"Scaling laws": ["Compute-optimal data-to-parameter ratio was roughly 20 tokens per parameter (Chinchilla).", "Inference cost now pushes teams to over-train smaller models."],
"Muon and modern optimizers": ["Newton-Schulz iterations approximate orthogonalisation cheaply.", "Usually combined with AdamW for embeddings and norms."],
"Data curation and synthetic data": ["Quality classifiers trained on curated seed data filter web crawls.", "Synthetic data risks collapse without real-data anchoring and verification."],
"Mid-training": ["Often includes long-context extension and instruction-like data.", "Sets up the base model for efficient RL later."],
"LoRA and parameter-efficient fine-tuning": ["Adapters are small files you can swap per customer or task.", "Higher ranks and all-layer adapters close most of the gap to full fine-tuning."],
"Fine-tuning toolkits and APIs": ["Start with SFT on a few thousand good examples before trying RL.", "Managed APIs hide distributed training but constrain algorithms."],
"Model merging": ["Works best between fine-tunes of the same base model.", "Popular for combining skills or languages cheaply."],
"Decentralized training": ["Workers train locally for many steps, then average updates.", "Enables training across datacenters and volunteer compute."],
"Build-it-yourself references": ["nanochat trains a small ChatGPT-like model end to end for a few hundred dollars.", "CS336 covers tokenizers, kernels, scaling and alignment from scratch."],
# inference
"Inference engines": ["Pick by hardware, model support and features (disaggregation, LoRA, structured output).", "Benchmark on your own traffic shape."],
"KV cache and PagedAttention": ["KV memory grows with batch size times sequence length.", "Paging enables sharing and near-zero waste."],
"Continuous batching and prefix caching": ["Keeps GPUs busy despite requests of different lengths.", "Prefix sharing is huge for agents with long common system prompts."],
"KV cache offloading": ["Turns re-prefill into a memory read.", "Tiered storage: HBM, CPU DRAM, local SSD, network."],
"Attention kernels": ["Tiling keeps data in fast on-chip SRAM.", "New versions target Hopper, Blackwell and FP8/FP4 paths."],
"On-device and edge inference": ["Privacy and offline use are the main drivers.", "Memory bandwidth, not compute, limits phone and laptop token rates."],
"LLM gateways and routers": ["Central place for keys, rate limits, logging and cost control.", "Routers send easy prompts to cheap models."],
"Inference benchmarking": ["Report throughput at a fixed latency target.", "Cost per million tokens depends on batch size and cache hit rate."],
# quant
"Microscaling formats": ["Shared 8-bit exponent scale per 32-element block.", "Supported by NVIDIA, AMD, Intel, Arm, Meta and Microsoft."],
"NVFP4": ["Smaller blocks and finer scales than MXFP4 improve accuracy.", "Increasingly used for pretraining as well as inference."],
"FP8 training and inference": ["E4M3 for weights and activations, E5M2 for gradients.", "Needs per-tensor or per-block scaling to avoid overflow."],
"Post-training quantization": ["4-bit weights with 16-bit activations is the common local setup.", "Always re-run your evals after quantizing."],
"Quantization-aware training": ["Fake-quantize in the forward pass, keep full-precision master weights.", "Recovers much of the accuracy lost to aggressive PTQ."],
"GGUF and local model formats": ["K-quants (Q4_K_M, Q5_K_M) balance size and quality.", "Metadata stores tokenizer and chat template in the file."],
"Ternary and 1-bit models": ["Matrix multiplies become additions and subtractions.", "Must be trained low-bit from the start."],
# hardware
"Scale-up vs. scale-out networking": ["Scale-up carries tensor and expert parallel traffic.", "Scale-out carries data-parallel gradients and inter-pod traffic."],
"Ultra Ethernet": ["UEC 1.0 specification released in 2025.", "Targets InfiniBand-class performance on Ethernet."],
"NVLink and NVLink Fusion": ["NVLink switches give all-to-all bandwidth inside a rack.", "Fusion opens the fabric to custom silicon partners."],
"CXL, PCIe and UCIe": ["CXL memory expansion adds capacity for KV caches and embeddings.", "UCIe lets vendors mix chiplets from different sources."],
"High-bandwidth memory": ["HBM4 doubles interface width versus HBM3.", "HBM supply is a key constraint on accelerator shipments."],
"Advanced packaging": ["Interposer size limits how much HBM fits beside a die.", "Packaging capacity expansions track AI demand closely."],
"Co-packaged optics": ["Shorter electrical paths mean lower power per bit.", "Early deployment in switches; accelerators later."],
"Custom accelerators": ["Hyperscalers design chips for their own inference fleets.", "Software ecosystem maturity is the main adoption hurdle."],
"AI factories, power and cooling": ["Racks exceed 100 kW; next-gen racks approach 600 kW.", "Grid access and power purchase deals shape site selection."],
"Kernel languages and compilers": ["Triton makes GPU kernels writable in Python-like code.", "Portable stacks reduce lock-in to one vendor."],
"Collective communication": ["Topology-aware algorithms (rings, trees) matter at scale.", "MoE all-to-all is latency-sensitive."],
"Model interchange formats": ["ONNX targets cross-runtime deployment.", "safetensors is the default on Hugging Face."],
"Hardware benchmarks": ["Compare systems on the same model and accuracy target.", "Vendor-submitted; read the fine print on configurations."],
# vlm
"VLM architecture": ["Visual token count drives cost: compress or pool where possible.", "Training stages: alignment, instruction tuning, then RL."],
"Open VLM families": ["Check licence, context length and video support.", "Evaluate on your own documents and images."],
"Native and dynamic resolution": ["Critical for small text, charts and screenshots.", "Token budget caps keep large images affordable."],
"Thinking with images": ["Tool calls like crop and zoom inside reasoning.", "Improves fine-grained detail questions."],
"Document AI and VLM-based OCR": ["Outputs Markdown with tables, formulas and reading order.", "Visual token compression can shrink long documents."],
"Visual document retrieval": ["Handles charts, layouts and scans that OCR mangles.", "Storage cost is higher than single-vector embeddings."],
"GUI grounding agents": ["Output click coordinates or element IDs.", "Benchmarks: ScreenSpot, OSWorld."],
"Omni and speech-to-speech models": ["End-to-end audio avoids ASR-LLM-TTS latency.", "Barge-in and turn detection are key UX problems."],
"Native image generation and editing": ["Autoregressive or hybrid with diffusion decoders.", "Multi-reference editing keeps characters and products consistent."],
"Multimodal evaluation": ["Document, chart, video and grounding need separate evals.", "Contamination is common in popular VQA sets."],
# embodied
"World models": ["Genie-style models generate playable 3D environments from prompts.", "Used for training agents and robots in simulation."],
"JEPA": ["Avoids wasting capacity on unpredictable pixel details.", "V-JEPA 2 adds action-conditioned planning with little robot data."],
"Robot simulation and sim-to-real": ["Domain randomisation bridges the reality gap.", "GPU-parallel simulation runs thousands of environments at once."],
"Diffusion transformers and flow matching": ["Flow matching learns straight paths from noise to data.", "Few-step distillation enables real-time generation."],
"Video generation": ["Native audio, longer clips and camera control arrived in 2025-26.", "Provenance marks (C2PA, SynthID) are standard on major services."],
# evals
"Eval harnesses": ["Inspect supports agents, sandboxes and scorers out of the box.", "Pin versions: prompts, tools, seeds and graders."],
"LLM-as-a-judge": ["Use pairwise comparisons and specific rubrics.", "Measure judge agreement with humans on a sample."],
"Agentic coding benchmarks": ["Verified subsets remove broken or ambiguous tasks.", "Watch for contamination of public repositories."],
"Agent and tool-use benchmarks": ["tau-bench tests policy-following with simulated users.", "Pass^k measures consistency across repeated attempts."],
"Frontier knowledge benchmarks": ["Designed by domain experts to resist search.", "Saturation arrives faster each generation."],
"Economic value evals": ["Tasks come with real deliverables (documents, spreadsheets, plans).", "Graded blind against expert work."],
"Task time horizon": ["Useful for forecasting when tasks of a given length become automatable.", "Reliability at 80% success lags the 50% horizon."],
"Leaderboards and trackers": ["Arena Elo reflects preference, not correctness.", "Cross-check with task-specific benchmarks."],
"Contamination and saturation": ["Use canary strings and private test sets.", "Prefer dynamic benchmarks refreshed over time."],
# safety
"AI for cyber defense": ["Automated vulnerability discovery and patch generation at scale.", "Access is gated to vetted defenders and critical-infrastructure operators."],
"Export controls on frontier models": ["Controls can change access overnight; plan fallbacks in production.", "Check provider status pages and statements for current availability."],
"Prompt injection and the lethal trifecta": ["No reliable model-only fix exists; design systems to limit blast radius.", "Separate privileged planning from untrusted data processing (CaMeL-style)."],
"MCP and tool security": ["Review tool descriptions like code.", "Use scoped tokens and least privilege per server."],
"Guardrails and classifiers": ["Layer defenses: input filter, model policy, output filter, monitoring.", "Tune for false positives, which frustrate legitimate users."],
"Mechanistic interpretability": ["Features are directions in activation space.", "Used for auditing, debugging and steering models."],
"Persona vectors and introspection": ["Monitor trait drift during fine-tuning.", "Preventative steering can stop unwanted traits being learned."],
"Chain-of-thought monitorability": ["Optimising against CoT monitors can teach models to hide reasoning.", "Monitor full trajectories, not only final actions."],
"Misalignment research": ["Tested in controlled simulations, not observed real-world harm.", "Informs evals that gate deployment."],
"Model welfare": ["Precautions include letting models end abusive conversations.", "Treated as uncertain, low-cost insurance."],
"Other regulation and standards": ["ISO 42001 offers certifiable AI management systems.", "SB 53 requires frontier developers to publish safety frameworks."],
"Government AI safety institutes": ["Run pre-deployment tests with labs.", "Publish open tools like Inspect."],
"Content provenance and watermarking": ["C2PA signs edit history; watermarks survive some edits.", "Neither alone proves content is authentic."],
# practice
"AI Engineer": ["Core skills: evals, context engineering, tool design, cost control.", "Bridges product, software and applied ML."],
"Services as software": ["Pricing shifts from seats to outcomes.", "Deployment expertise becomes the scarce input."],
"Prompt engineering and prompt optimization": ["Be explicit, give examples, specify format, explain why.", "Optimisers like GEPA evolve prompts using eval feedback."],
"Eval-driven development": ["Start with error analysis on real traces.", "Keep a small, fast regression suite plus deeper periodic evals."],
"LLMOps and observability": ["Trace trees show each agent step and its cost.", "Link user feedback to traces for triage."],
"Human-in-the-loop and approval design": ["Approve irreversible or external actions; auto-allow sandboxed reads.", "Batch approvals to reduce fatigue."],
"Open weights vs. open source AI": ["Licences vary: MIT and Apache vs custom community licences.", "Fully open (data plus code) enables real reproducibility."],
}
